// Auto-generated by parse_django_models.py — do not edit by hand.
// Regenerate with: .venv/bin/python scripts/parse_django_models.py --force

/**
 * @fileoverview Precompiled entity registry for API and sync workers.
 *
 * All entity metadata — fields, relationships, joinColumns, and cached
 * field lookups — are computed at generation time. Zero runtime derivation.
 */

/** @type {EntityMeta} */
const _entity_org = {
    tag: "org",
    table: "peeringdb_organization",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "name", type: "string" },
        { name: "aka", type: "string" },
        { name: "name_long", type: "string" },
        { name: "website", type: "string" },
        { name: "social_media", type: "json", queryable: false, json: true },
        { name: "notes", type: "string" },
        { name: "logo", type: "string", queryable: false, nullable: true },
        { name: "address1", type: "string", queryable: false },
        { name: "address2", type: "string", queryable: false },
        { name: "city", type: "string" },
        { name: "country", type: "string" },
        { name: "state", type: "string" },
        { name: "zipcode", type: "string" },
        { name: "floor", type: "string", queryable: false },
        { name: "suite", type: "string", queryable: false },
        { name: "latitude", type: "number", queryable: false },
        { name: "longitude", type: "number", queryable: false },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [
        { field: "campus_set", table: "peeringdb_campus", fk: "org_id" },
        { field: "fac_set", table: "peeringdb_facility", fk: "org_id" },
        { field: "net_set", table: "peeringdb_network", fk: "org_id" },
        { field: "ix_set", table: "peeringdb_ix", fk: "org_id" },
        { field: "carrier_set", table: "peeringdb_carrier", fk: "org_id" }
    ],
    _columns: ["id", "name", "aka", "name_long", "website", "social_media", "notes", "logo", "address1", "address2", "city", "country", "state", "zipcode", "floor", "suite", "latitude", "longitude", "created", "updated", "status"],
    _jsonColumns: new Set(["social_media"]),
    _boolColumns: new Set([]),
    _nullableColumns: new Set(["logo"]),
    _fieldNames: new Set(["address1", "address2", "aka", "city", "country", "created", "floor", "id", "latitude", "logo", "longitude", "name", "name_long", "notes", "social_media", "state", "status", "suite", "updated", "website", "zipcode"]),
    _filterTypes: new Map([["id", "number"], ["name", "string"], ["aka", "string"], ["name_long", "string"], ["website", "string"], ["notes", "string"], ["city", "string"], ["country", "string"], ["state", "string"], ["zipcode", "string"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_campus = {
    tag: "campus",
    table: "peeringdb_campus",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "name", type: "string" },
        { name: "name_long", type: "string", nullable: true },
        { name: "aka", type: "string", nullable: true },
        { name: "website", type: "string" },
        { name: "social_media", type: "json", queryable: false, json: true },
        { name: "notes", type: "string" },
        { name: "org_id", type: "number", foreignKey: "org" },
        { name: "org_name", type: "string", queryable: false },
        { name: "country", type: "string", queryable: false },
        { name: "city", type: "string", queryable: false },
        { name: "zipcode", type: "string", queryable: false },
        { name: "state", type: "string", queryable: false },
        { name: "logo", type: "string", queryable: false, nullable: true },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [
        { field: "fac_set", table: "peeringdb_facility", fk: "campus_id" }
    ],
    _columns: ["id", "name", "name_long", "aka", "website", "social_media", "notes", "org_id", "org_name", "country", "city", "zipcode", "state", "logo", "created", "updated", "status"],
    _jsonColumns: new Set(["social_media"]),
    _boolColumns: new Set([]),
    _nullableColumns: new Set(["aka", "logo", "name_long"]),
    _fieldNames: new Set(["aka", "city", "country", "created", "id", "logo", "name", "name_long", "notes", "org_id", "org_name", "social_media", "state", "status", "updated", "website", "zipcode"]),
    _filterTypes: new Map([["id", "number"], ["name", "string"], ["name_long", "string"], ["aka", "string"], ["website", "string"], ["notes", "string"], ["org_id", "number"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_fac = {
    tag: "fac",
    table: "peeringdb_facility",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "name", type: "string" },
        { name: "website", type: "string" },
        { name: "social_media", type: "json", queryable: false, json: true },
        { name: "aka", type: "string" },
        { name: "name_long", type: "string" },
        { name: "clli", type: "string" },
        { name: "rencode", type: "string" },
        { name: "npanxx", type: "string" },
        { name: "tech_email", type: "string" },
        { name: "tech_phone", type: "string" },
        { name: "sales_email", type: "string" },
        { name: "sales_phone", type: "string" },
        { name: "property", type: "string", nullable: true },
        { name: "diverse_serving_substations", type: "boolean", nullable: true },
        { name: "available_voltage_services", type: "json", queryable: false, json: true },
        { name: "notes", type: "string" },
        { name: "region_continent", type: "string", nullable: true },
        { name: "status_dashboard", type: "string", nullable: true },
        { name: "org_id", type: "number", foreignKey: "org" },
        { name: "campus_id", type: "number", nullable: true, foreignKey: "campus" },
        { name: "org_name", type: "string", queryable: false },
        { name: "net_count", type: "number" },
        { name: "ix_count", type: "number" },
        { name: "carrier_count", type: "number" },
        { name: "logo", type: "string", queryable: false, nullable: true },
        { name: "address1", type: "string", queryable: false },
        { name: "address2", type: "string", queryable: false },
        { name: "city", type: "string" },
        { name: "country", type: "string" },
        { name: "state", type: "string" },
        { name: "zipcode", type: "string" },
        { name: "floor", type: "string", queryable: false },
        { name: "suite", type: "string", queryable: false },
        { name: "latitude", type: "number", queryable: false },
        { name: "longitude", type: "number", queryable: false },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [
        { field: "carrierfac_set", table: "peeringdb_ix_carrier_facility", fk: "fac_id" },
        { field: "ixfac_set", table: "peeringdb_ix_facility", fk: "fac_id", joinColumns: [{ table: "peeringdb_ix", localFk: "ix_id", columns: { "name": "ix_name" } }] },
        { field: "netfac_set", table: "peeringdb_network_facility", fk: "fac_id", joinColumns: [{ table: "peeringdb_network", localFk: "net_id", columns: { "name": "net_name", "asn": "net_asn" } }] },
        { field: "netixlan_set", table: "peeringdb_network_ixlan", fk: "net_side_id", joinColumns: [{ table: "peeringdb_network", localFk: "net_id", columns: { "name": "net_name" } }] },
        { field: "netixlan_set", table: "peeringdb_network_ixlan", fk: "ix_side_id", joinColumns: [{ table: "peeringdb_network", localFk: "net_id", columns: { "name": "net_name" } }] }
    ],
    _columns: ["id", "name", "website", "social_media", "aka", "name_long", "clli", "rencode", "npanxx", "tech_email", "tech_phone", "sales_email", "sales_phone", "property", "diverse_serving_substations", "available_voltage_services", "notes", "region_continent", "status_dashboard", "org_id", "campus_id", "org_name", "net_count", "ix_count", "carrier_count", "logo", "address1", "address2", "city", "country", "state", "zipcode", "floor", "suite", "latitude", "longitude", "created", "updated", "status"],
    _jsonColumns: new Set(["available_voltage_services", "social_media"]),
    _boolColumns: new Set(["diverse_serving_substations"]),
    _nullableColumns: new Set(["campus_id", "diverse_serving_substations", "logo", "property", "region_continent", "status_dashboard"]),
    _fieldNames: new Set(["address1", "address2", "aka", "available_voltage_services", "campus_id", "carrier_count", "city", "clli", "country", "created", "diverse_serving_substations", "floor", "id", "ix_count", "latitude", "logo", "longitude", "name", "name_long", "net_count", "notes", "npanxx", "org_id", "org_name", "property", "region_continent", "rencode", "sales_email", "sales_phone", "social_media", "state", "status", "status_dashboard", "suite", "tech_email", "tech_phone", "updated", "website", "zipcode"]),
    _filterTypes: new Map([["id", "number"], ["name", "string"], ["website", "string"], ["aka", "string"], ["name_long", "string"], ["clli", "string"], ["rencode", "string"], ["npanxx", "string"], ["tech_email", "string"], ["tech_phone", "string"], ["sales_email", "string"], ["sales_phone", "string"], ["property", "string"], ["diverse_serving_substations", "boolean"], ["notes", "string"], ["region_continent", "string"], ["status_dashboard", "string"], ["org_id", "number"], ["campus_id", "number"], ["net_count", "number"], ["ix_count", "number"], ["carrier_count", "number"], ["city", "string"], ["country", "string"], ["state", "string"], ["zipcode", "string"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_net = {
    tag: "net",
    table: "peeringdb_network",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "asn", type: "number" },
        { name: "name", type: "string" },
        { name: "aka", type: "string" },
        { name: "name_long", type: "string" },
        { name: "irr_as_set", type: "string" },
        { name: "website", type: "string" },
        { name: "social_media", type: "json", queryable: false, json: true },
        { name: "looking_glass", type: "string" },
        { name: "route_server", type: "string" },
        { name: "notes", type: "string" },
        { name: "notes_private", type: "string" },
        { name: "info_traffic", type: "string" },
        { name: "info_ratio", type: "string" },
        { name: "info_scope", type: "string" },
        { name: "info_types", type: "json", queryable: false, json: true },
        { name: "info_prefixes4", type: "number", nullable: true },
        { name: "info_prefixes6", type: "number", nullable: true },
        { name: "info_unicast", type: "boolean" },
        { name: "info_multicast", type: "boolean" },
        { name: "info_ipv6", type: "boolean" },
        { name: "info_never_via_route_servers", type: "boolean" },
        { name: "policy_url", type: "string" },
        { name: "policy_general", type: "string" },
        { name: "policy_locations", type: "string" },
        { name: "policy_ratio", type: "boolean" },
        { name: "policy_contracts", type: "string" },
        { name: "status_dashboard", type: "string", nullable: true },
        { name: "rir_status", type: "string", nullable: true },
        { name: "rir_status_updated", type: "datetime", nullable: true },
        { name: "org_id", type: "number", foreignKey: "org", resolve: { "name": "org_name" } },
        { name: "info_type", type: "string", queryable: false },
        { name: "ix_count", type: "number" },
        { name: "fac_count", type: "number" },
        { name: "netixlan_updated", type: "datetime" },
        { name: "netfac_updated", type: "datetime" },
        { name: "poc_updated", type: "datetime" },
        { name: "allow_ixp_update", type: "boolean" },
        { name: "logo", type: "string", queryable: false, nullable: true },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: [{ table: "peeringdb_organization", localFk: "org_id", columns: { "name": "org_name" } }],
    relationships: [
        { field: "poc_set", table: "peeringdb_network_contact", fk: "net_id" },
        { field: "netfac_set", table: "peeringdb_network_facility", fk: "net_id" },
        { field: "netixlan_set", table: "peeringdb_network_ixlan", fk: "net_id" }
    ],
    _columns: ["id", "asn", "name", "aka", "name_long", "irr_as_set", "website", "social_media", "looking_glass", "route_server", "notes", "notes_private", "info_traffic", "info_ratio", "info_scope", "info_types", "info_prefixes4", "info_prefixes6", "info_unicast", "info_multicast", "info_ipv6", "info_never_via_route_servers", "policy_url", "policy_general", "policy_locations", "policy_ratio", "policy_contracts", "status_dashboard", "rir_status", "rir_status_updated", "org_id", "info_type", "ix_count", "fac_count", "netixlan_updated", "netfac_updated", "poc_updated", "allow_ixp_update", "logo", "created", "updated", "status"],
    _jsonColumns: new Set(["info_types", "social_media"]),
    _boolColumns: new Set(["allow_ixp_update", "info_ipv6", "info_multicast", "info_never_via_route_servers", "info_unicast", "policy_ratio"]),
    _nullableColumns: new Set(["info_prefixes4", "info_prefixes6", "logo", "rir_status", "rir_status_updated", "status_dashboard"]),
    _fieldNames: new Set(["aka", "allow_ixp_update", "asn", "created", "fac_count", "id", "info_ipv6", "info_multicast", "info_never_via_route_servers", "info_prefixes4", "info_prefixes6", "info_ratio", "info_scope", "info_traffic", "info_type", "info_types", "info_unicast", "irr_as_set", "ix_count", "logo", "looking_glass", "name", "name_long", "netfac_updated", "netixlan_updated", "notes", "notes_private", "org_id", "poc_updated", "policy_contracts", "policy_general", "policy_locations", "policy_ratio", "policy_url", "rir_status", "rir_status_updated", "route_server", "social_media", "status", "status_dashboard", "updated", "website"]),
    _filterTypes: new Map([["id", "number"], ["asn", "number"], ["name", "string"], ["aka", "string"], ["name_long", "string"], ["irr_as_set", "string"], ["website", "string"], ["looking_glass", "string"], ["route_server", "string"], ["notes", "string"], ["notes_private", "string"], ["info_traffic", "string"], ["info_ratio", "string"], ["info_scope", "string"], ["info_prefixes4", "number"], ["info_prefixes6", "number"], ["info_unicast", "boolean"], ["info_multicast", "boolean"], ["info_ipv6", "boolean"], ["info_never_via_route_servers", "boolean"], ["policy_url", "string"], ["policy_general", "string"], ["policy_locations", "string"], ["policy_ratio", "boolean"], ["policy_contracts", "string"], ["status_dashboard", "string"], ["rir_status", "string"], ["rir_status_updated", "datetime"], ["org_id", "number"], ["ix_count", "number"], ["fac_count", "number"], ["netixlan_updated", "datetime"], ["netfac_updated", "datetime"], ["poc_updated", "datetime"], ["allow_ixp_update", "boolean"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_ix = {
    tag: "ix",
    table: "peeringdb_ix",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "name", type: "string" },
        { name: "aka", type: "string" },
        { name: "name_long", type: "string" },
        { name: "city", type: "string" },
        { name: "country", type: "string" },
        { name: "notes", type: "string" },
        { name: "region_continent", type: "string" },
        { name: "media", type: "string" },
        { name: "proto_unicast", type: "boolean" },
        { name: "proto_multicast", type: "boolean" },
        { name: "proto_ipv6", type: "boolean" },
        { name: "website", type: "string" },
        { name: "social_media", type: "json", queryable: false, json: true },
        { name: "url_stats", type: "string" },
        { name: "tech_email", type: "string" },
        { name: "tech_phone", type: "string" },
        { name: "policy_email", type: "string" },
        { name: "policy_phone", type: "string" },
        { name: "sales_email", type: "string" },
        { name: "sales_phone", type: "string" },
        { name: "ixf_net_count", type: "number" },
        { name: "ixf_last_import", type: "datetime", nullable: true },
        { name: "service_level", type: "string" },
        { name: "terms", type: "string" },
        { name: "status_dashboard", type: "string", nullable: true },
        { name: "org_id", type: "number", foreignKey: "org", resolve: { "name": "org_name" } },
        { name: "net_count", type: "number" },
        { name: "fac_count", type: "number" },
        { name: "ixf_import_request", type: "datetime" },
        { name: "ixf_import_request_status", type: "string" },
        { name: "logo", type: "string", queryable: false, nullable: true },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: [{ table: "peeringdb_organization", localFk: "org_id", columns: { "name": "org_name" } }],
    relationships: [
        { field: "ixfac_set", table: "peeringdb_ix_facility", fk: "ix_id" },
        { field: "ixlan_set", table: "peeringdb_ixlan", fk: "ix_id" }
    ],
    _columns: ["id", "name", "aka", "name_long", "city", "country", "notes", "region_continent", "media", "proto_unicast", "proto_multicast", "proto_ipv6", "website", "social_media", "url_stats", "tech_email", "tech_phone", "policy_email", "policy_phone", "sales_email", "sales_phone", "ixf_net_count", "ixf_last_import", "service_level", "terms", "status_dashboard", "org_id", "net_count", "fac_count", "ixf_import_request", "ixf_import_request_status", "logo", "created", "updated", "status"],
    _jsonColumns: new Set(["social_media"]),
    _boolColumns: new Set(["proto_ipv6", "proto_multicast", "proto_unicast"]),
    _nullableColumns: new Set(["ixf_last_import", "logo", "status_dashboard"]),
    _fieldNames: new Set(["aka", "city", "country", "created", "fac_count", "id", "ixf_import_request", "ixf_import_request_status", "ixf_last_import", "ixf_net_count", "logo", "media", "name", "name_long", "net_count", "notes", "org_id", "policy_email", "policy_phone", "proto_ipv6", "proto_multicast", "proto_unicast", "region_continent", "sales_email", "sales_phone", "service_level", "social_media", "status", "status_dashboard", "tech_email", "tech_phone", "terms", "updated", "url_stats", "website"]),
    _filterTypes: new Map([["id", "number"], ["name", "string"], ["aka", "string"], ["name_long", "string"], ["city", "string"], ["country", "string"], ["notes", "string"], ["region_continent", "string"], ["media", "string"], ["proto_unicast", "boolean"], ["proto_multicast", "boolean"], ["proto_ipv6", "boolean"], ["website", "string"], ["url_stats", "string"], ["tech_email", "string"], ["tech_phone", "string"], ["policy_email", "string"], ["policy_phone", "string"], ["sales_email", "string"], ["sales_phone", "string"], ["ixf_net_count", "number"], ["ixf_last_import", "datetime"], ["service_level", "string"], ["terms", "string"], ["status_dashboard", "string"], ["org_id", "number"], ["net_count", "number"], ["fac_count", "number"], ["ixf_import_request", "datetime"], ["ixf_import_request_status", "string"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_carrier = {
    tag: "carrier",
    table: "peeringdb_carrier",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "name", type: "string" },
        { name: "aka", type: "string" },
        { name: "name_long", type: "string" },
        { name: "website", type: "string" },
        { name: "social_media", type: "json", queryable: false, json: true },
        { name: "notes", type: "string" },
        { name: "org_id", type: "number", foreignKey: "org" },
        { name: "org_name", type: "string", queryable: false },
        { name: "fac_count", type: "number", queryable: false },
        { name: "logo", type: "string", queryable: false, nullable: true },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [
        { field: "carrierfac_set", table: "peeringdb_ix_carrier_facility", fk: "carrier_id" }
    ],
    _columns: ["id", "name", "aka", "name_long", "website", "social_media", "notes", "org_id", "org_name", "fac_count", "logo", "created", "updated", "status"],
    _jsonColumns: new Set(["social_media"]),
    _boolColumns: new Set([]),
    _nullableColumns: new Set(["logo"]),
    _fieldNames: new Set(["aka", "created", "fac_count", "id", "logo", "name", "name_long", "notes", "org_id", "org_name", "social_media", "status", "updated", "website"]),
    _filterTypes: new Map([["id", "number"], ["name", "string"], ["aka", "string"], ["name_long", "string"], ["website", "string"], ["notes", "string"], ["org_id", "number"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_carrierfac = {
    tag: "carrierfac",
    table: "peeringdb_ix_carrier_facility",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "carrier_id", type: "number", foreignKey: "carrier" },
        { name: "fac_id", type: "number", foreignKey: "fac" },
        { name: "name", type: "string", queryable: false },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [],
    _columns: ["id", "carrier_id", "fac_id", "name", "created", "updated", "status"],
    _jsonColumns: new Set([]),
    _boolColumns: new Set([]),
    _nullableColumns: new Set([]),
    _fieldNames: new Set(["carrier_id", "created", "fac_id", "id", "name", "status", "updated"]),
    _filterTypes: new Map([["id", "number"], ["carrier_id", "number"], ["fac_id", "number"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_ixfac = {
    tag: "ixfac",
    table: "peeringdb_ix_facility",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "ix_id", type: "number", foreignKey: "ix", resolve: { "name": "ix_name" } },
        { name: "fac_id", type: "number", foreignKey: "fac" },
        { name: "name", type: "string", queryable: false },
        { name: "city", type: "string", queryable: false },
        { name: "country", type: "string", queryable: false },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: [{ table: "peeringdb_ix", localFk: "ix_id", columns: { "name": "ix_name" } }],
    relationships: [],
    _columns: ["id", "ix_id", "fac_id", "name", "city", "country", "created", "updated", "status"],
    _jsonColumns: new Set([]),
    _boolColumns: new Set([]),
    _nullableColumns: new Set([]),
    _fieldNames: new Set(["city", "country", "created", "fac_id", "id", "ix_id", "name", "status", "updated"]),
    _filterTypes: new Map([["id", "number"], ["ix_id", "number"], ["fac_id", "number"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_ixlan = {
    tag: "ixlan",
    table: "peeringdb_ixlan",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "name", type: "string" },
        { name: "descr", type: "string" },
        { name: "mtu", type: "number" },
        { name: "vlan", type: "number", nullable: true },
        { name: "dot1q_support", type: "boolean" },
        { name: "rs_asn", type: "number", nullable: true },
        { name: "arp_sponge", type: "string", nullable: true },
        { name: "ixf_ixp_member_list_url", type: "string", nullable: true },
        { name: "ixf_ixp_member_list_url_visible", type: "string" },
        { name: "ix_id", type: "number", foreignKey: "ix" },
        { name: "ixf_ixp_import_enabled", type: "boolean" },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [
        { field: "ixpfx_set", table: "peeringdb_ixlan_prefix", fk: "ixlan_id" },
        { field: "netixlan_set", table: "peeringdb_network_ixlan", fk: "ixlan_id", joinColumns: [{ table: "peeringdb_network", localFk: "net_id", columns: { "name": "net_name" } }] }
    ],
    _columns: ["id", "name", "descr", "mtu", "vlan", "dot1q_support", "rs_asn", "arp_sponge", "ixf_ixp_member_list_url", "ixf_ixp_member_list_url_visible", "ix_id", "ixf_ixp_import_enabled", "created", "updated", "status"],
    _jsonColumns: new Set([]),
    _boolColumns: new Set(["dot1q_support", "ixf_ixp_import_enabled"]),
    _nullableColumns: new Set(["arp_sponge", "ixf_ixp_member_list_url", "rs_asn", "vlan"]),
    _fieldNames: new Set(["arp_sponge", "created", "descr", "dot1q_support", "id", "ix_id", "ixf_ixp_import_enabled", "ixf_ixp_member_list_url", "ixf_ixp_member_list_url_visible", "mtu", "name", "rs_asn", "status", "updated", "vlan"]),
    _filterTypes: new Map([["id", "number"], ["name", "string"], ["descr", "string"], ["mtu", "number"], ["vlan", "number"], ["dot1q_support", "boolean"], ["rs_asn", "number"], ["arp_sponge", "string"], ["ixf_ixp_member_list_url", "string"], ["ixf_ixp_member_list_url_visible", "string"], ["ix_id", "number"], ["ixf_ixp_import_enabled", "boolean"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_ixpfx = {
    tag: "ixpfx",
    table: "peeringdb_ixlan_prefix",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "notes", type: "string" },
        { name: "protocol", type: "string" },
        { name: "prefix", type: "string" },
        { name: "in_dfz", type: "boolean" },
        { name: "ixlan_id", type: "number", foreignKey: "ixlan" },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [],
    _columns: ["id", "notes", "protocol", "prefix", "in_dfz", "ixlan_id", "created", "updated", "status"],
    _jsonColumns: new Set([]),
    _boolColumns: new Set(["in_dfz"]),
    _nullableColumns: new Set([]),
    _fieldNames: new Set(["created", "id", "in_dfz", "ixlan_id", "notes", "prefix", "protocol", "status", "updated"]),
    _filterTypes: new Map([["id", "number"], ["notes", "string"], ["protocol", "string"], ["prefix", "string"], ["in_dfz", "boolean"], ["ixlan_id", "number"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_poc = {
    tag: "poc",
    table: "peeringdb_network_contact",
    _restricted: true,
    _anonFilter: { field: "visible", value: "Public" },
    fields: [
        { name: "id", type: "number" },
        { name: "role", type: "string" },
        { name: "visible", type: "string" },
        { name: "name", type: "string" },
        { name: "phone", type: "string" },
        { name: "email", type: "string" },
        { name: "url", type: "string" },
        { name: "net_id", type: "number", foreignKey: "net" },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: undefined,
    relationships: [],
    _columns: ["id", "role", "visible", "name", "phone", "email", "url", "net_id", "created", "updated", "status"],
    _jsonColumns: new Set([]),
    _boolColumns: new Set([]),
    _nullableColumns: new Set([]),
    _fieldNames: new Set(["created", "email", "id", "name", "net_id", "phone", "role", "status", "updated", "url", "visible"]),
    _filterTypes: new Map([["id", "number"], ["role", "string"], ["visible", "string"], ["name", "string"], ["phone", "string"], ["email", "string"], ["url", "string"], ["net_id", "number"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_netfac = {
    tag: "netfac",
    table: "peeringdb_network_facility",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "avail_sonet", type: "boolean" },
        { name: "avail_ethernet", type: "boolean" },
        { name: "avail_atm", type: "boolean" },
        { name: "net_id", type: "number", foreignKey: "net", resolve: { "name": "net_name", "asn": "net_asn" } },
        { name: "fac_id", type: "number", foreignKey: "fac" },
        { name: "name", type: "string" },
        { name: "city", type: "string" },
        { name: "country", type: "string" },
        { name: "local_asn", type: "string", queryable: false },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: [{ table: "peeringdb_network", localFk: "net_id", columns: { "name": "net_name", "asn": "net_asn" } }],
    relationships: [],
    _columns: ["id", "avail_sonet", "avail_ethernet", "avail_atm", "net_id", "fac_id", "name", "city", "country", "local_asn", "created", "updated", "status"],
    _jsonColumns: new Set([]),
    _boolColumns: new Set(["avail_atm", "avail_ethernet", "avail_sonet"]),
    _nullableColumns: new Set([]),
    _fieldNames: new Set(["avail_atm", "avail_ethernet", "avail_sonet", "city", "country", "created", "fac_id", "id", "local_asn", "name", "net_id", "status", "updated"]),
    _filterTypes: new Map([["id", "number"], ["avail_sonet", "boolean"], ["avail_ethernet", "boolean"], ["avail_atm", "boolean"], ["net_id", "number"], ["fac_id", "number"], ["name", "string"], ["city", "string"], ["country", "string"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/** @type {EntityMeta} */
const _entity_netixlan = {
    tag: "netixlan",
    table: "peeringdb_network_ixlan",
    _restricted: false,
    _anonFilter: undefined,
    fields: [
        { name: "id", type: "number" },
        { name: "asn", type: "number" },
        { name: "ipaddr4", type: "string", nullable: true },
        { name: "ipaddr6", type: "string", nullable: true },
        { name: "is_rs_peer", type: "boolean" },
        { name: "bfd_support", type: "boolean" },
        { name: "notes", type: "string" },
        { name: "speed", type: "number" },
        { name: "operational", type: "boolean" },
        { name: "net_id", type: "number", foreignKey: "net", resolve: { "name": "net_name" } },
        { name: "ixlan_id", type: "number", foreignKey: "ixlan" },
        { name: "net_side_id", type: "number", nullable: true, foreignKey: "fac" },
        { name: "ix_side_id", type: "number", nullable: true, foreignKey: "fac" },
        { name: "ix_id", type: "number" },
        { name: "name", type: "string" },
        { name: "created", type: "datetime" },
        { name: "updated", type: "datetime" },
        { name: "status", type: "string" }
    ],
    joinColumns: [{ table: "peeringdb_network", localFk: "net_id", columns: { "name": "net_name" } }],
    relationships: [],
    _columns: ["id", "asn", "ipaddr4", "ipaddr6", "is_rs_peer", "bfd_support", "notes", "speed", "operational", "net_id", "ixlan_id", "net_side_id", "ix_side_id", "ix_id", "name", "created", "updated", "status"],
    _jsonColumns: new Set([]),
    _boolColumns: new Set(["bfd_support", "is_rs_peer", "operational"]),
    _nullableColumns: new Set(["ipaddr4", "ipaddr6", "ix_side_id", "net_side_id"]),
    _fieldNames: new Set(["asn", "bfd_support", "created", "id", "ipaddr4", "ipaddr6", "is_rs_peer", "ix_id", "ix_side_id", "ixlan_id", "name", "net_id", "net_side_id", "notes", "operational", "speed", "status", "updated"]),
    _filterTypes: new Map([["id", "number"], ["asn", "number"], ["ipaddr4", "string"], ["ipaddr6", "string"], ["is_rs_peer", "boolean"], ["bfd_support", "boolean"], ["notes", "string"], ["speed", "number"], ["operational", "boolean"], ["net_id", "number"], ["ixlan_id", "number"], ["net_side_id", "number"], ["ix_side_id", "number"], ["ix_id", "number"], ["name", "string"], ["created", "datetime"], ["updated", "datetime"], ["status", "string"]]),
};

/**
 * Maps an API endpoint tag to its precompiled entity metadata.
 * @type {Record<string, EntityMeta>}
 */
export const ENTITIES = { "org": _entity_org, "campus": _entity_campus, "fac": _entity_fac, "net": _entity_net, "ix": _entity_ix, "carrier": _entity_carrier, "carrierfac": _entity_carrierfac, "ixfac": _entity_ixfac, "ixlan": _entity_ixlan, "ixpfx": _entity_ixpfx, "poc": _entity_poc, "netfac": _entity_netfac, "netixlan": _entity_netixlan };

/**
 * Set of valid entity tags for fast lookup in the router.
 * @type {Set<string>}
 */
export const ENTITY_TAGS = new Set(["org", "campus", "fac", "net", "ix", "carrier", "carrierfac", "ixfac", "ixlan", "ixpfx", "poc", "netfac", "netixlan"]);

// ── Cache tier configuration ─────────────────────────────────────────────

const MB = 1024 * 1024;

/**
 * Default cache tier for entities not in CACHE_TIERS.
 * New entities from upstream automatically get this bucket.
 * @type {{slots: number, maxSize: number}}
 */
export const DEFAULT_TIER = { slots: 128, maxSize: 1 * MB };

/**
 * Per-entity cache tier configuration.
 * Sized by query cardinality (slots) and measured response outliers (maxSize).
 * @type {Record<string, {slots: number, maxSize: number}>}
 */
export const CACHE_TIERS = {
    "net": { slots: 1024, maxSize: 16 * MB },
    "netixlan": { slots: 2048, maxSize: 16 * MB },
    "netfac": { slots: 512, maxSize: 8 * MB },
    "fac": { slots: 512, maxSize: 4 * MB },
    "ix": { slots: 512, maxSize: 4 * MB },
    "org": { slots: 512, maxSize: 8 * MB },
    "poc": { slots: 256, maxSize: 1 * MB }
};

