-- Migration: schema 3.7.0+2.80.1
-- Changes: peeringdb_network.ixp_update_exclude, peeringdb_network.ixp_update_exclude_speed, peeringdb_network.ixp_update_exclude_is_rs_peer, peeringdb_network.ixp_update_exclude_operational
--
-- Auto-generated by diff_schema.py. Review before applying.

ALTER TABLE "peeringdb_network" ADD COLUMN "ixp_update_exclude" TEXT NOT NULL DEFAULT '';
ALTER TABLE "peeringdb_network" ADD COLUMN "ixp_update_exclude_speed" BOOL NOT NULL DEFAULT 0;
ALTER TABLE "peeringdb_network" ADD COLUMN "ixp_update_exclude_is_rs_peer" BOOL NOT NULL DEFAULT 0;
ALTER TABLE "peeringdb_network" ADD COLUMN "ixp_update_exclude_operational" BOOL NOT NULL DEFAULT 0;
