-- Migration: schema 3.7.0+2.83.0
-- Changes: peeringdb_network.rtbh_community, peeringdb_network.preferred_ip_mtu, peeringdb_network_ixlan.rfc8950, peeringdb_network_ixlan.planned_status_change_status, peeringdb_network_ixlan.planned_status_change_date
--
-- Auto-generated by diff_schema.py. Review before applying.

ALTER TABLE "peeringdb_network" ADD COLUMN "rtbh_community" TEXT NOT NULL DEFAULT '';
ALTER TABLE "peeringdb_network" ADD COLUMN "preferred_ip_mtu" INTEGER;
ALTER TABLE "peeringdb_network_ixlan" ADD COLUMN "rfc8950" BOOL;
ALTER TABLE "peeringdb_network_ixlan" ADD COLUMN "planned_status_change_status" TEXT NOT NULL DEFAULT '';
ALTER TABLE "peeringdb_network_ixlan" ADD COLUMN "planned_status_change_date" TEXT NOT NULL DEFAULT '';
