/**
 * @fileoverview Request handler routes.
 */

import { r2Get } from '../../core/r2.js';
import { serveR2, isNotModified } from '../../core/http.js';
import { getDistroIndex, setDistroIndex, warmRamCacheFromRelease } from '../indexes.js';
import { isHex64 } from '../../core/utils.js';
import { H_CACHED, H_IMMUTABLE, EMPTY_GZ, EMPTY_GZ_HASH, EMPTY_HASH } from '../../core/constants.js';
import { metaCache, dataCache } from '../cache.js';

/**
 * Handles explicit requests for static repository assets assigned to the path execution root.
 * Generates synthetic caching headers directly for config payloads avoiding heavy R2 fetches.
 *
 * @param {string} rawPath - The requested relative path string.
 * @param {DebthinEnv} env - The Cloudflare environment bindings.
 * @param {Request} request - The inbound HTTP request.
 * @param {string} CONFIG_JSON_STRING - The JSON configuration string.
 * @returns {Promise<Response>} The HTTP Response object.
 */
export async function handleStaticAssets(rawPath, env, request, CONFIG_JSON_STRING) {
  if (rawPath === "config.json") {
    const etag = `W/"${CONFIG_JSON_STRING.length}"`;
    if (isNotModified(request.headers, { etag })) {
      return new Response(null, { status: 304, headers: { ...H_CACHED, "ETag": etag } });
    }

    const hc = new Headers(H_CACHED);
    hc.set("Content-Type", "application/json; charset=utf-8");
    hc.set("ETag", etag);
    hc.set("X-Debthin", "hit-synthetic");
    hc.set("X-Cache", "HIT");
    hc.set("X-Cache-Hits", "0");
    return new Response(CONFIG_JSON_STRING, { headers: hc });
  }
  const file = rawPath === "" ? "index.html" : rawPath;
  return serveR2(env, request, file, metaCache);
}

/**
 * Issues an HTTP 301 redirect for requests targeting the /pool/ directory.
 * Instructs the apt client to fetch the binary directly from the upstream mirror, avoiding Cloudflare egress costs.
 *
 * @param {string} protocol - The request protocol (http or https).
 * @param {string} upstream - The target mirror hostname.
 * @param {string} rest - The object path segment after /pool/.
 * @returns {Response} The HTTP 301 redirect response.
 */
export function handleUpstreamRedirect(protocol, upstream, rest) {
  return new Response(null, {
    status: 301,
    headers: { "Location": `${protocol}://${upstream}/${rest}` }
  });
}

/**
 * Resolves content by inspecting the by-hash-index files generated by the ingest script.
 * Maintains a lazily-loaded reference map of hashes to relative file paths.
 * Intercepts calls for empty files and serves them exclusively from memory to bypass R2 charges.
 *
 * @param {Request} request - The inbound HTTP request.
 * @param {DebthinEnv} env - The Cloudflare environment bindings.
 * @param {ExecutionContext} ctx - The worker execution context.
 * @param {string} distro - The Linux distribution name.
 * @param {string} sha256 - The requested SHA256 file hash.
 * @returns {Promise<Response|null>} The resolved file content or null.
 */
export async function handleByHash(request, env, ctx, distro, sha256) {
  if (sha256 === EMPTY_GZ_HASH) {
    const heg = new Headers(H_IMMUTABLE);
    heg.set("Content-Type", "application/x-gzip");
    heg.set("X-Debthin", "hit-synthetic");
    return new Response(request.method === "HEAD" ? null : /** @type {*} */ (EMPTY_GZ), { headers: heg });
  }
  if (sha256 === EMPTY_HASH) {
    const hep = new Headers(H_IMMUTABLE);
    hep.set("Content-Type", "text/plain; charset=utf-8");
    hep.set("X-Debthin", "hit-synthetic");
    return new Response("", { headers: hep });
  }

  if (sha256.length === 64 && isHex64(sha256)) {
    let distroIndex = getDistroIndex(distro);

    if (!distroIndex || distroIndex instanceof Promise) {
      if (!distroIndex) {
        const promise = r2Get(env, `dists/${distro}/by-hash-index.json`, metaCache, ctx).then(async obj => {
          const json = obj ? JSON.parse(await obj.text()) : {};
          const current = getDistroIndex(distro);
          const freshData = (current instanceof Promise || !current) ? {} : current;
          return Object.assign(Object.create(null), json, freshData);
        }).catch(() => {
          if (getDistroIndex(distro) === promise) setDistroIndex(distro, null);
          return {};
        });
        setDistroIndex(distro, promise);
        distroIndex = promise;
      }
      distroIndex = await distroIndex;
      setDistroIndex(distro, distroIndex);
    }

    const relPath = distroIndex[sha256];
    if (relPath) return serveR2(env, request, `dists/${distro}/${relPath}`, relPath.includes("Packages") ? dataCache : metaCache, { immutable: true });
    return new Response("Not found\n", { status: 404 });
  }

  return null;
}

/**
 * Handles manifest retrieval for InRelease and Release metadata requests.
 *
 * @param {DebthinEnv} env - The Cloudflare environment bindings.
 * @param {Request} request - The inbound HTTP request.
 * @param {string} r2Key - The target bucket evaluation path.
 * @param {string} p2 - The matched token component string.
 * @param {ExecutionContext} ctx - The worker execution context.
 * @returns {Promise<Response|null>} Processed route or null.
 */
async function serveManifests(env, request, r2Key, p2, ctx) {
  const suiteDir = r2Key.slice(0, r2Key.lastIndexOf("/"));
  if (p2 === "InRelease" || p2 === "Release.gpg") {
    return serveR2(env, request, r2Key, metaCache, {
      ctx,
      ttl: 120000,
      maxAge: 120,
      onDiskMiss: (/** @type {ArrayBuffer} */ buf, /** @type {boolean} */ force) => warmRamCacheFromRelease(buf, suiteDir, force)
    });
  }
  if (p2 === "Release") {
    const fetchKey = r2Key.replace("Release", "InRelease");
    return serveR2(env, request, r2Key, metaCache, {
      fetchKey,
      transform: "strip-pgp",
      ctx,
      ttl: 120000,
      maxAge: 120,
      onDiskMiss: (/** @type {ArrayBuffer} */ buf, /** @type {boolean} */ force) => warmRamCacheFromRelease(buf, suiteDir, force)
    });
  }
  return null;
}

/**
 * Delivers generated component binaries or handles generic decompression mapping.
 *
 * @param {DebthinEnv} env - The Cloudflare environment bindings.
 * @param {Request} request - The inbound HTTP request.
 * @param {string} r2Key - The target bucket evaluation path.
 * @param {string} p1 - First chunk representation.
 * @param {string} p2 - Second chunk representation.
 * @param {string} p3 - Third chunk representation.
 * @param {string} p4 - Final payload locator index fragment.
 * @returns {Promise<Response|null>} Processed route or null.
 */
async function serveComponents(env, request, r2Key, p1, p2, p3, p4) {
  if (p4 === "Release") {
    const hbr = new Headers(H_CACHED);
    hbr.set("Content-Type", "text/plain; charset=utf-8");
    hbr.set("X-Debthin", "hit-generated");
    hbr.set("X-Cache", "HIT");
    hbr.set("X-Cache-Hits", "0");
    return new Response(`Archive: ${p1}\nComponent: ${p2}\nArchitecture: ${p3.slice(7)}\n`, { headers: hbr });
  }
  if (p4 === "Packages") {
    return serveR2(env, request, r2Key, dataCache, { fetchKey: r2Key + ".gz", transform: "decompress" });
  }
  if (p4 === "Packages.gz" || p4 === "Packages.lz4" || p4 === "Packages.xz") {
    return serveR2(env, request, r2Key, dataCache);
  }
  return null;
}

/**
 * Core dispatch engine for distribution-level files.
 * Re-maps paths for legacy aliases, strips PGP signatures from InRelease files when Release is requested,
 * and automatically decompresses Packages.gz payload streams internally when uncompressed Packages are requested.
 *
 * @param {Request} request - The inbound HTTP request.
 * @param {DebthinEnv} env - The Cloudflare environment bindings.
 * @param {ExecutionContext} ctx - The worker execution context.
 * @param {string} distro - The Linux distribution name.
 * @param {string} suitePath - The remaining path fragments.
 * @param {Record<string, string>} tokens - Zero-allocation parsed path parts.
 * @param {Record<string, any>} distroConfig - Distribution parameters from config.json.
 * @returns {Promise<Response|null>} Processed HTTP Response or null fallback.
 */
export async function handleDistributionHashIndex(request, env, ctx, distro, suitePath, { p1, p2, p3, p4 }, distroConfig) {
  const r2Key = `dists/${distro}/${suitePath.slice(6)}`;

  if (!p3) return serveManifests(env, request, r2Key, p2, ctx);

  const { components, arches } = distroConfig;

  // Packages & Hashes (dists/debian/.../binary-amd64/...)
  if (p3 && (components.has(p2) || p2 === "headless") && p3.startsWith("binary-") && arches.has(p3.slice(7))) {
    const resp = await serveComponents(env, request, r2Key, p1, p2, p3, p4);
    if (resp) return resp;
  }

  const byHashIdx = suitePath.indexOf("/by-hash/SHA256/");
  if (byHashIdx !== -1) {
    const sha256 = suitePath.slice(byHashIdx + 16);
    return handleByHash(request, env, ctx, distro, sha256);
  }

  // Not processed natively, redirect to upstream
  return null;
}