/**
 * @fileoverview Unit tests for the /status endpoint.
 * Validates that the handler reads _sync_meta and returns
 * the expected JSON structure with CORS and cache headers.
 *
 * The /status endpoint is served from a pre-encoded buffer
 * generated by sync_state.js. Because sync_state is a module-level
 * singleton, the first test that calls /status triggers a cold-boot
 * D1 query that populates the cached state. Subsequent tests serve
 * from that cached buffer (with background refresh that has no effect
 * in the test environment since waitUntil is a no-op).
 *
 * These tests therefore focus on the cold-boot path by running
 * a single canonical scenario first, then testing response structure
 * and headers on subsequent calls.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

// ── Mock D1 ────────────────────────────────────────────────────

/**
 * Builds a mock D1 database that returns the given rows from
 * any SELECT on _sync_meta. Includes all columns required by
 * sync_state.js (including last_modified_at).
 *
 * @param {Array<{entity: string, last_sync: number, row_count: number, updated_at: string, last_modified_at: number}>} rows
 * @returns {{prepare: Function}}
 */
function mockDB(rows) {
    const db = {
        prepare(_sql) {
            return {
                all() {
                    return Promise.resolve({ results: rows });
                }
            };
        },
        /** Sessions API: returns itself since the mock already has .prepare(). */
        withSession() { return db; }
    };
    return db;
}

// ── Import the worker under test ────────────────────────────────

const workerModule = await import('../../../api/index.js');
const worker = workerModule.default;

/**
 * Sends a GET request to the worker and returns the response.
 *
 * @param {string} path - URL path (e.g. "/status").
 * @param {{}} [env] - Environment bindings.
 * @returns {Promise<Response>}
 */
async function get(path, env = {}) {
    const request = new Request(`https://test-host${path}`, { method: 'GET' });
    Object.defineProperty(request, 'cf', { value: { colo: 'TEST' } });
    const ctx = { waitUntil: () => {} };
    return worker.fetch(request, env, ctx);
}

// ── Tests ───────────────────────────────────────────────────────

describe('/status endpoint', () => {

    // This test runs first and populates the sync_state singleton.
    // The mock includes representative entities with distinct timestamps
    // so we can verify the max-finding and per-entity structure.
    it('returns 200 with sync metadata on cold boot', async () => {
        const env = {
            PDB: mockDB([
                { entity: 'fac', last_sync: 1743520000, row_count: 8500, updated_at: '2026-04-01 14:00:00', last_modified_at: 1743516000 },
                { entity: 'net', last_sync: 1743520200, row_count: 42000, updated_at: '2026-04-01 14:30:00', last_modified_at: 1743520200 },
            ])
        };

        const res = await get('/status', env);
        assert.equal(res.status, 200);

        const body = await res.json();
        assert.ok(body.sync, 'response should have a sync object');
        assert.ok(body.sync.entities, 'should have entities object');
        // Verify net was included with the correct data
        assert.equal(body.sync.entities.net.row_count, 42000);
        assert.equal(body.sync.entities.net.last_sync, 1743520200);
        assert.equal(body.sync.entities.fac.last_sync, 1743520000);
        // last_modified_at should be the max across all entities
        assert.equal(body.sync.last_modified_at, 1743520200);
    });

    it('returns correct Content-Type and CORS headers', async () => {
        // Uses cached payload from previous test — env doesn't matter
        const env = { PDB: mockDB([]) };

        const res = await get('/status', env);
        assert.match(res.headers.get('Content-Type'), /application\/json/);
        assert.equal(res.headers.get('Access-Control-Allow-Origin'), '*');
    });

    it('includes all ENTITY_TAGS in the response', async () => {
        const env = { PDB: mockDB([]) };

        const res = await get('/status', env);
        const body = await res.json();

        // The response should include every known entity tag,
        // even if _sync_meta had no row for it (defaults to 0/'')
        assert.ok(body.sync.entities.net, 'should have net');
        assert.ok(body.sync.entities.fac, 'should have fac');
        assert.ok(body.sync.entities.ix, 'should have ix');
        assert.ok(body.sync.entities.org, 'should have org');
    });

    it('serves consistent response from cached buffer', async () => {
        const env = { PDB: mockDB([]) };

        // Two requests should return identical payloads (same buffer)
        const res1 = await get('/status', env);
        const res2 = await get('/status', env);
        const body1 = await res1.text();
        const body2 = await res2.text();
        assert.equal(body1, body2);
    });
});
