#!/usr/bin/env python3
"""
Schema diff tool: compares generated schema.sql against the previous
committed version and produces ALTER TABLE migration SQL for new
columns and tables.

Reads the previous schema from git (HEAD:extracted/schema.sql) and
compares against the current extracted/schema.sql. Generates a
numbered migration file in database/migrations/ if there are changes.

Usage:
    .venv/bin/python scripts/diff_schema.py [--dry-run]

    --dry-run   Print the migration SQL but don't write the file.
"""

import json
import re
import subprocess
import sys
from pathlib import Path


# ── SQL parsing ──────────────────────────────────────────────────────────────

# Matches: CREATE TABLE IF NOT EXISTS "tablename" (
TABLE_RE = re.compile(
    r'CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+"([^"]+)"\s*\(',
    re.IGNORECASE,
)

# Matches a column definition line:  "colname" TYPE ...
COLUMN_RE = re.compile(r'^\s+"([^"]+)"\s+(.+)$')

# Matches: CREATE INDEX IF NOT EXISTS "indexname" ON "tablename" ...
INDEX_RE = re.compile(
    r'(CREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+"[^"]+"\s+ON\s+"([^"]+)"\s*\([^)]+\)\s*;)',
    re.IGNORECASE,
)


def parse_schema(sql):
    """
    Parse a schema.sql string into a dict of:
      { table_name: { col_name: "TYPE DEFAULT ..." } }

    Also returns a dict of table_name → full CREATE TABLE block and
    a dict of table_name → list of CREATE INDEX statements.

    Args:
        sql: Full schema.sql content.

    Returns:
        Tuple of (columns_dict, create_blocks_dict, indexes_dict).
    """
    columns = {}
    blocks = {}
    indexes = {}

    # Extract CREATE TABLE blocks
    # Split on CREATE TABLE to get each block
    parts = re.split(r'(?=CREATE\s+TABLE)', sql, flags=re.IGNORECASE)
    for part in parts:
        m = TABLE_RE.search(part)
        if not m:
            continue
        table = m.group(1)
        if table.startswith("_"):
            continue  # Skip meta tables

        columns[table] = {}
        # Find the block between ( and );
        paren_start = part.index("(", m.end() - 1)
        paren_end = part.index(");", paren_start)
        body = part[paren_start + 1 : paren_end]

        for line in body.split("\n"):
            cm = COLUMN_RE.match(line.rstrip(","))
            if cm:
                col_name = cm.group(1)
                col_def = cm.group(2).rstrip(",")
                columns[table][col_name] = col_def

        # Store the full CREATE block (up to and including the closing ;)
        block_end = part.index(");") + 2
        blocks[table] = part[:block_end].strip()

    # Extract indexes
    for m in INDEX_RE.finditer(sql):
        stmt = m.group(1)
        table = m.group(2)
        if table.startswith("_"):
            continue
        indexes.setdefault(table, []).append(stmt)

    return columns, blocks, indexes


def generate_migration(old_sql, new_sql, schema_version):
    """
    Compare old and new schema SQL and produce migration statements.

    Handles:
      - New tables: full CREATE TABLE + indexes
      - New columns on existing tables: ALTER TABLE ADD COLUMN

    Args:
        old_sql: Previous schema.sql content (from git HEAD).
        new_sql: Current schema.sql content.
        schema_version: Combined version string for the migration name.

    Returns:
        Tuple of (migration_sql, description) or (None, None) if no changes.
    """
    old_cols, _, _ = parse_schema(old_sql)
    new_cols, new_blocks, new_indexes = parse_schema(new_sql)

    stmts = []
    descriptions = []

    # New tables
    for table in sorted(new_cols.keys()):
        if table not in old_cols:
            stmts.append(new_blocks[table])
            for idx in new_indexes.get(table, []):
                stmts.append(idx)
            descriptions.append(f"new table: {table}")

    # New columns on existing tables
    for table in sorted(new_cols.keys()):
        if table not in old_cols:
            continue
        for col in new_cols[table]:
            if col not in old_cols[table]:
                col_def = new_cols[table][col]
                # ALTER TABLE ADD COLUMN can't have NOT NULL without
                # a default in SQLite, so strip NOT NULL if no DEFAULT
                if "NOT NULL" in col_def and "DEFAULT" not in col_def:
                    col_def = col_def.replace("NOT NULL ", "")
                stmts.append(
                    f'ALTER TABLE "{table}" ADD COLUMN "{col}" {col_def};'
                )
                descriptions.append(f"{table}.{col}")

    if not stmts:
        return None, None

    header = [
        f"-- Migration: schema {schema_version}",
        f"-- Changes: {', '.join(descriptions)}",
        "--",
        "-- Auto-generated by diff_schema.py. Review before applying.",
        "",
    ]

    return "\n".join(header + stmts) + "\n", "; ".join(descriptions)


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    """
    Compare current schema.sql against git HEAD and generate a migration
    file if there are differences.
    """
    project_root = Path(__file__).parent.parent
    schema_path = project_root / "extracted" / "schema.sql"
    entities_path = project_root / "extracted" / "entities.json"
    migrations_dir = project_root / "database" / "migrations"
    dry_run = "--dry-run" in sys.argv

    if not schema_path.exists():
        print("No extracted/schema.sql found. Run parse_django_models.py first.")
        sys.exit(1)

    new_sql = schema_path.read_text()

    # Get the previous version from git
    try:
        result = subprocess.run(
            ["git", "show", "HEAD:extracted/schema.sql"],
            capture_output=True, text=True, check=True,
            cwd=project_root,
        )
        old_sql = result.stdout
    except subprocess.CalledProcessError:
        print("No previous schema.sql in git HEAD. Skipping diff.")
        return

    # Read schema version from entities.json
    schema_version = "unknown"
    if entities_path.exists():
        try:
            data = json.loads(entities_path.read_text())
            schema_version = data.get("schema_version", "unknown")
        except (json.JSONDecodeError, KeyError):
            pass

    migration_sql, description = generate_migration(old_sql, new_sql, schema_version)

    if migration_sql is None:
        print("No schema changes detected.")
        return

    print(f"Schema changes: {description}")

    if dry_run:
        print("\n--- Migration SQL (dry run) ---")
        print(migration_sql)
        return

    # Determine next migration number
    migrations_dir.mkdir(parents=True, exist_ok=True)
    existing = sorted(migrations_dir.glob("*.sql"))
    if existing:
        last_num = int(existing[-1].name.split("_")[0])
    else:
        last_num = 0

    next_num = last_num + 1
    safe_version = schema_version.replace("+", "_").replace(".", "-")
    filename = f"{next_num:03d}_auto_{safe_version}.sql"
    migration_path = migrations_dir / filename

    migration_path.write_text(migration_sql)
    print(f"Wrote {migration_path}")


if __name__ == "__main__":
    main()
