#!/usr/bin/env bash
# migrate-to-d1.sh — Build a clean PeeringDB database and import into Cloudflare D1.
#
# Part of the cold-start bootstrap sequence. See docs/deployment.md for the
# full procedure including resource provisioning and post-import steps.
#
# Pipeline:
#   1. Download JSON dumps from public.peeringdb.com (--fetch)
#   2. Build a local SQLite database from the dumps using schema.sql
#   3. Fix referential integrity (delete orphans, null dangling FKs)
#   4. Verify — count remaining violations (must be zero)
#   5. Push the clean data to D1 (--remote for production)
#   6. Populate _sync_meta with initial row counts
#
# schema.sql is generated by the pipeline and already includes all current
# columns (__vector_embedded, __logo_migrated, etc.). Migrations in
# database/migrations/ are only needed to upgrade an existing database —
# not required after a fresh migrate-to-d1.sh run.
#
# Prerequisites:
#   - wrangler CLI installed and authenticated
#   - D1 database already created (wrangler d1 create peeringdb)
#   - python3 and sqlite3 available
#   - JSON files in database/ (download with --fetch, or manually via curl)
#
# Usage:
#   ./scripts/migrate-to-d1.sh [--remote] [--fetch]
#
# --remote   Push to production D1 (default: local dev database)
# --fetch    Download fresh JSON dumps from public.peeringdb.com before importing.

set -euo pipefail

# Work around root-owned files in ~/.npm by using a local cache
export NPM_CONFIG_CACHE="${NPM_CONFIG_CACHE:-$(cd "$(dirname "$0")/.." && pwd)/workers/.npm-cache}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SCHEMA_SQL="$REPO_ROOT/extracted/schema.sql"
FK_CLEANUP_SQL="$SCRIPT_DIR/lib/fk_cleanup.sql"
FK_VERIFY_SQL="$SCRIPT_DIR/lib/fk_verify.sql"
WRANGLER_CONFIG="$REPO_ROOT/workers/wrangler.toml"
PUBLIC_BASE="https://public.peeringdb.com"
JSON_TO_SQL="$SCRIPT_DIR/json_to_sql.py"
DB_DIR="$REPO_ROOT/database"
LOCAL_DB="$DB_DIR/database.sqlite"

# Parse flags
REMOTE_FLAG=""
DO_FETCH=false
for arg in "$@"; do
    case "$arg" in
        --remote) REMOTE_FLAG="--remote" ;;
        --fetch)  DO_FETCH=true ;;
        *) echo "Unknown flag: $arg"; exit 1 ;;
    esac
done

if [[ -n "$REMOTE_FLAG" ]]; then
    echo "==> Operating against PRODUCTION D1 database"
else
    echo "==> Operating against LOCAL D1 dev database"
fi

if [[ ! -f "$WRANGLER_CONFIG" ]]; then
    echo "ERROR: Wrangler config not found at $WRANGLER_CONFIG" >&2
    exit 1
fi

TMPDIR_EXPORT="$REPO_ROOT/.d1-migration-tmp"
mkdir -p "$TMPDIR_EXPORT"
trap 'rm -rf "$TMPDIR_EXPORT"' EXIT

# ── Entity definitions ────────────────────────────────────────────────────────
# tag:table — order matters: parents before children for FK integrity.

ENTITIES=(
    "org:peeringdb_organization"
    "campus:peeringdb_campus"
    "fac:peeringdb_facility"
    "carrier:peeringdb_carrier"
    "ix:peeringdb_ix"
    "ixlan:peeringdb_ixlan"
    "ixpfx:peeringdb_ixlan_prefix"
    "net:peeringdb_network"
    "poc:peeringdb_network_contact"
    "netfac:peeringdb_network_facility"
    "netixlan:peeringdb_network_ixlan"
    "ixfac:peeringdb_ix_facility"
    "carrierfac:peeringdb_ix_carrier_facility"
)

# ── Step 1: Fetch JSON dumps ─────────────────────────────────────────────────

if $DO_FETCH; then
    echo "==> Fetching JSON dumps from public.peeringdb.com..."
    for ENTITY_DEF in "${ENTITIES[@]}"; do
        IFS=':' read -r TAG TABLE <<< "$ENTITY_DEF"
        echo "    $TAG..."
        curl -sf --retry 3 --retry-delay 5 --max-time 120 \
            "${PUBLIC_BASE}/${TAG}-0.json" -o "$DB_DIR/${TAG}.json"
    done
fi

# ── Step 2: Build local SQLite ────────────────────────────────────────────────

echo "==> Building local SQLite database..."
rm -f "$LOCAL_DB"
sqlite3 "$LOCAL_DB" < "$SCHEMA_SQL"

for ENTITY_DEF in "${ENTITIES[@]}"; do
    IFS=':' read -r TAG TABLE <<< "$ENTITY_DEF"
    JSON_FILE="$DB_DIR/${TAG}.json"

    if [[ ! -f "$JSON_FILE" ]]; then
        echo "ERROR: $JSON_FILE not found. Run with --fetch or download manually." >&2
        exit 1
    fi

    EXPORT_FILE="$TMPDIR_EXPORT/${TABLE}.sql"
    python3 "$JSON_TO_SQL" "$JSON_FILE" "$TABLE" > "$EXPORT_FILE"
    ROW_COUNT=$(wc -l < "$EXPORT_FILE" | tr -d ' ')
    echo "    $TAG: $ROW_COUNT rows"

    if [[ "$ROW_COUNT" -gt 0 ]]; then
        sqlite3 "$LOCAL_DB" < "$EXPORT_FILE"
    fi
done

# ── Step 3: Fix referential integrity ─────────────────────────────────────────

echo "==> Fixing referential integrity..."
sqlite3 "$LOCAL_DB" < "$FK_CLEANUP_SQL"
echo "    Done."

# ── Step 4: Verify ────────────────────────────────────────────────────────────

echo "==> Verifying referential integrity..."
VIOLATIONS=$(sqlite3 "$LOCAL_DB" < "$FK_VERIFY_SQL")
echo "$VIOLATIONS" | while IFS='|' read -r fk count; do
    if [[ "$count" -gt 0 ]]; then
        echo "    FAIL: $fk = $count violations"
    fi
done

TOTAL=$(echo "$VIOLATIONS" | awk -F'|' '{s+=$2} END {print s}')
if [[ "$TOTAL" -gt 0 ]]; then
    echo "ERROR: $TOTAL FK violations remain after cleanup. Aborting D1 import." >&2
    exit 1
fi
echo "    Clean (0 violations)."

# ── Step 5: Row counts after cleanup ─────────────────────────────────────────

echo "==> Row counts after cleanup:"
for ENTITY_DEF in "${ENTITIES[@]}"; do
    IFS=':' read -r TAG TABLE <<< "$ENTITY_DEF"
    COUNT=$(sqlite3 "$LOCAL_DB" "SELECT COUNT(*) FROM \"$TABLE\"")
    printf "    %-12s %s\n" "$TAG" "$COUNT"
done

# ── Step 6: Push to D1 ───────────────────────────────────────────────────────

echo "==> Applying schema to D1..."
npx wrangler d1 execute peeringdb \
    --config "$WRANGLER_CONFIG" \
    $REMOTE_FLAG \
    --yes \
    --file "$SCHEMA_SQL"

echo "==> Importing data to D1..."
for ENTITY_DEF in "${ENTITIES[@]}"; do
    IFS=':' read -r TAG TABLE <<< "$ENTITY_DEF"
    EXPORT_FILE="$TMPDIR_EXPORT/${TABLE}.sql"

    ROW_COUNT=$(wc -l < "$EXPORT_FILE" | tr -d ' ')
    if [[ "$ROW_COUNT" -eq 0 ]]; then
        echo "    $TAG: (empty, skipping)"
        continue
    fi

    echo "    $TAG: $ROW_COUNT rows..."
    npx wrangler d1 execute peeringdb \
        --config "$WRANGLER_CONFIG" \
        $REMOTE_FLAG \
        --yes \
        --file "$EXPORT_FILE"
done

echo "==> Applying FK cleanup to D1..."
npx wrangler d1 execute peeringdb \
    --config "$WRANGLER_CONFIG" \
    $REMOTE_FLAG \
    --yes \
    --file "$FK_CLEANUP_SQL"

# ── Populate _sync_meta ──────────────────────────────────────────────────────

echo "==> Populating _sync_meta..."
SYNC_FILE="$TMPDIR_EXPORT/sync_meta.sql"
> "$SYNC_FILE"

for ENTITY_DEF in "${ENTITIES[@]}"; do
    IFS=':' read -r TAG TABLE _ <<< "$ENTITY_DEF"
    # Use the local SQLite row count (after cleanup) for accuracy
    ROW_COUNT=$(sqlite3 "$LOCAL_DB" "SELECT COUNT(*) FROM \"$TABLE\"")
    echo "INSERT OR REPLACE INTO _sync_meta (entity, last_sync, row_count, updated_at, last_modified_at) VALUES ('${TAG}', strftime('%s','now'), ${ROW_COUNT}, datetime('now'), 0);" >> "$SYNC_FILE"
done

npx wrangler d1 execute peeringdb \
    --config "$WRANGLER_CONFIG" \
    $REMOTE_FLAG \
    --yes \
    --file "$SYNC_FILE"

echo "==> Migration complete."
exit 0
