#!/usr/bin/env python3
"""
Patch all override files with translations for the 145 PDBFE-specific strings
that are not in the upstream PeeringDB Weblate catalogue.

Run once from the project root:
    source .venv/bin/activate
    python scripts/patch_overrides.py
"""

import json, pathlib, sys

OVERRIDES_DIR = pathlib.Path("frontend/locales/overrides")

# ── New translations ──────────────────────────────────────────────────────────
# Format: { "English key": { "lang_code": "translation", ... }, ... }
# Keys that are the same in all languages (proper nouns, technical terms) are
# represented with a single "*" entry used as the default.

TRANSLATIONS = {
    # ── Single-word / short labels ──────────────────────────────────────────
    "Auto": {
        "de": "Automatisch", "fr": "Automatique", "es": "Automático",
        "it": "Automatico", "pt": "Automático", "nl": "Automatisch",
        "ru": "Авто", "zh-cn": "自动", "zh-tw": "自動",
        "ja": "自動", "cs": "Automaticky", "el": "Αυτόματο",
        "lt": "Automatiškai", "ro": "Automat",
    },
    "Dark": {
        "de": "Dunkel", "fr": "Sombre", "es": "Oscuro",
        "it": "Scuro", "pt": "Escuro",
        "ru": "Тёмная", "zh-cn": "深色", "zh-tw": "深色",
        "ja": "ダーク", "cs": "Tmavý", "el": "Σκοτεινό",
        "lt": "Tamsi", "ro": "Întunecat",
    },
    "Light": {
        "de": "Hell", "fr": "Clair", "es": "Claro",
        "it": "Chiaro", "pt": "Claro",
        "ru": "Светлая", "zh-cn": "浅色", "zh-tw": "淺色",
        "ja": "ライト", "cs": "Světlý", "el": "Φωτεινό",
        "lt": "Šviesi", "ro": "Deschis",
    },
    "Theme": {
        "de": "Design", "fr": "Thème", "es": "Tema",
        "it": "Tema", "pt": "Tema",
        "ru": "Тема", "zh-cn": "主题", "zh-tw": "主題",
        "ja": "テーマ", "cs": "Motiv", "el": "Θέμα",
        "lt": "Tema", "ro": "Temă",
    },
    "Map": {
        "de": "Karte", "fr": "Carte", "es": "Mapa",
        "it": "Mappa", "pt": "Mapa",
        "ru": "Карта", "zh-cn": "地图", "zh-tw": "地圖",
        "ja": "地図", "cs": "Mapa", "el": "Χάρτης",
        "lt": "Žemėlapis", "ro": "Hartă",
    },
    "Share": {
        "de": "Teilen", "fr": "Partager", "es": "Compartir",
        "it": "Condividi", "pt": "Partilhar",
        "ru": "Поделиться", "zh-cn": "分享", "zh-tw": "分享",
        "ja": "共有", "cs": "Sdílet", "el": "Κοινοποίηση",
        "lt": "Dalintis", "ro": "Partajare",
    },
    "Search": {
        "de": "Suche", "fr": "Recherche", "es": "Búsqueda",
        "it": "Cerca", "pt": "Pesquisar",
        "ru": "Поиск", "zh-cn": "搜索", "zh-tw": "搜尋",
        "ja": "検索", "cs": "Hledat", "el": "Αναζήτηση",
        "lt": "Paieška", "ro": "Căutare",
    },
    "Compare": {
        "de": "Vergleichen", "fr": "Comparer", "es": "Comparar",
        "it": "Confronta", "pt": "Comparar",
        "ru": "Сравнить", "zh-cn": "对比", "zh-tw": "比較",
        "ja": "比較", "cs": "Porovnat", "el": "Σύγκριση",
        "lt": "Palyginti", "ro": "Comparare",
    },
    "Favorites": {
        "de": "Favoriten", "fr": "Favoris", "es": "Favoritos",
        "it": "Preferiti", "pt": "Favoritos",
        "ru": "Избранное", "zh-cn": "收藏夹", "zh-tw": "我的最愛",
        "ja": "お気に入り", "cs": "Oblíbené", "el": "Αγαπημένα",
        "lt": "Mėgstami", "ro": "Favorite",
    },
    "Remove": {
        "de": "Entfernen", "fr": "Supprimer", "es": "Eliminar",
        "it": "Rimuovi", "pt": "Remover",
        "ru": "Удалить", "zh-cn": "删除", "zh-tw": "移除",
        "ja": "削除", "cs": "Odstranit", "el": "Αφαίρεση",
        "lt": "Pašalinti", "ro": "Eliminare",
    },
    "Reset": {
        "de": "Zurücksetzen", "fr": "Réinitialiser", "es": "Restablecer",
        "it": "Reimposta", "pt": "Repor",
        "ru": "Сбросить", "zh-cn": "重置", "zh-tw": "重設",
        "ja": "リセット", "cs": "Obnovit", "el": "Επαναφορά",
        "lt": "Iš naujo", "ro": "Resetare",
    },
    "Rows": {
        "de": "Zeilen", "fr": "Lignes", "es": "Filas",
        "it": "Righe", "pt": "Linhas",
        "ru": "Строки", "zh-cn": "行", "zh-tw": "行",
        "ja": "行", "cs": "Řádky", "el": "Γραμμές",
        "lt": "Eilutės", "ro": "Rânduri",
    },
    "Entity": {
        "de": "Entität", "fr": "Entité", "es": "Entidad",
        "it": "Entità", "pt": "Entidade",
        "ru": "Объект", "zh-cn": "实体", "zh-tw": "實體",
        "ja": "エンティティ", "cs": "Entita", "el": "Οντότητα",
        "lt": "Subjektas", "ro": "Entitate",
    },
    "Path": {
        "de": "Pfad", "fr": "Chemin", "es": "Ruta",
        "it": "Percorso", "pt": "Caminho",
        "ru": "Путь", "zh-cn": "路径", "zh-tw": "路徑",
        "ja": "パス", "cs": "Cesta", "el": "Διαδρομή",
        "lt": "Kelias", "ro": "Cale",
    },
    "Request": {
        "de": "Anfrage", "fr": "Requête", "es": "Solicitud",
        "it": "Richiesta", "pt": "Solicitação",
        "ru": "Запрос", "zh-cn": "请求", "zh-tw": "請求",
        "ja": "リクエスト", "cs": "Požadavek", "el": "Αίτημα",
        "lt": "Užklausa", "ro": "Cerere",
    },
    "Hits": {
        "de": "Treffer", "fr": "Hits", "es": "Hits",
        "it": "Risultati", "pt": "Acessos",
        "ru": "Запросы", "zh-cn": "命中次数", "zh-tw": "命中數",
        "ja": "ヒット数", "cs": "Přístupy", "el": "Επισκέψεις",
        "lt": "Užklausos", "ro": "Accesări",
    },
    "Age": {
        "de": "Alter", "fr": "Âge", "es": "Antigüedad",
        "it": "Età", "pt": "Idade",
        "ru": "Возраст", "zh-cn": "时间", "zh-tw": "時間",
        "ja": "経過時間", "cs": "Stáří", "el": "Ηλικία",
        "lt": "Amžius", "ro": "Vechime",
    },
    "Time": {
        "de": "Zeit", "fr": "Heure", "es": "Hora",
        "it": "Ora", "pt": "Hora",
        "ru": "Время", "zh-cn": "时间", "zh-tw": "時間",
        "ja": "時刻", "cs": "Čas", "el": "Ώρα",
        "lt": "Laikas", "ro": "Oră",
    },
    "Timezone": {
        "de": "Zeitzone", "fr": "Fuseau horaire", "es": "Zona horaria",
        "it": "Fuso orario", "pt": "Fuso horário",
        "ru": "Часовой пояс", "zh-cn": "时区", "zh-tw": "時區",
        "ja": "タイムゾーン", "cs": "Časové pásmo", "el": "Ζώνη ώρας",
        "lt": "Laiko juosta", "ro": "Fus orar",
    },
    "Updated": {
        "de": "Aktualisiert", "fr": "Mis à jour", "es": "Actualizado",
        "it": "Aggiornato", "pt": "Atualizado",
        "ru": "Обновлено", "zh-cn": "已更新", "zh-tw": "已更新",
        "ja": "更新済み", "cs": "Aktualizováno", "el": "Ενημερώθηκε",
        "lt": "Atnaujinta", "ro": "Actualizat",
    },
    "Only": {
        "de": "Nur", "fr": "Seulement", "es": "Solo",
        "it": "Solo", "pt": "Apenas",
        "ru": "Только", "zh-cn": "仅限", "zh-tw": "僅限",
        "ja": "のみ", "cs": "Pouze", "el": "Μόνο",
        "lt": "Tik", "ro": "Numai",
    },
    "Edge": {
        "de": "Edge", "fr": "Edge", "es": "Edge",
        "it": "Edge", "pt": "Edge",
        "ru": "Edge", "zh-cn": "边缘", "zh-tw": "邊緣",
        "ja": "エッジ", "cs": "Edge", "el": "Edge",
        "lt": "Edge", "ro": "Edge",
    },
    "Cache": {
        "de": "Cache", "fr": "Cache", "es": "Caché",
        "it": "Cache", "pt": "Cache",
        "ru": "Кэш", "zh-cn": "缓存", "zh-tw": "快取",
        "ja": "キャッシュ", "cs": "Mezipaměť", "el": "Κρυφή μνήμη",
        "lt": "Talpykla", "ro": "Cache",
    },
    "Isolate": {
        "de": "Isolieren", "fr": "Isoler", "es": "Aislar",
        "it": "Isola", "pt": "Isolar",
        "ru": "Изолировать", "zh-cn": "隔离", "zh-tw": "隔離",
        "ja": "切り離し", "cs": "Izolovat", "el": "Απομόνωση",
        "lt": "Atskirti", "ro": "Izolare",
    },
    "Sign in": {
        "de": "Anmelden", "fr": "Se connecter", "es": "Iniciar sesión",
        "it": "Accedi", "pt": "Entrar",
        "ru": "Войти", "zh-cn": "登录", "zh-tw": "登入",
        "ja": "ログイン", "cs": "Přihlásit se", "el": "Σύνδεση",
        "lt": "Prisijungti", "ro": "Autentificare",
    },
    "Dismiss": {
        "de": "Schließen", "fr": "Ignorer", "es": "Descartar",
        "it": "Chiudi", "pt": "Dispensar",
        "ru": "Закрыть", "zh-cn": "关闭", "zh-tw": "關閉",
        "ja": "閉じる", "cs": "Zavřít", "el": "Απόρριψη",
        "lt": "Uždaryti", "ro": "Închide",
    },
    # ── Short phrases ─────────────────────────────────────────────────────────
    "vs": {
        "de": "vs.", "fr": "vs", "es": "vs.",
        "it": "vs", "pt": "vs",
        "ru": "против", "zh-cn": "对比", "zh-tw": "對比",
        "ja": "対", "cs": "vs.", "el": "εναντίον",
        "lt": "prieš", "ro": "vs.",
    },
    "entries": {
        "de": "Einträge", "fr": "entrées", "es": "entradas",
        "it": "voci", "pt": "entradas",
        "ru": "записей", "zh-cn": "条记录", "zh-tw": "筆記錄",
        "ja": "件", "cs": "záznamů", "el": "εγγραφές",
        "lt": "įrašų", "ro": "intrări",
    },
    "pages": {
        "de": "Seiten", "fr": "pages", "es": "páginas",
        "it": "pagine", "pt": "páginas",
        "ru": "страниц", "zh-cn": "页", "zh-tw": "頁",
        "ja": "ページ", "cs": "stránek", "el": "σελίδες",
        "lt": "puslapių", "ro": "pagini",
    },
    "missing from": {
        "de": "fehlt in", "fr": "absent de", "es": "ausente en",
        "it": "assente in", "pt": "ausente em",
        "ru": "отсутствует в", "zh-cn": "缺少于", "zh-tw": "缺少於",
        "ja": "不在:", "cs": "chybí v", "el": "λείπει από",
        "lt": "trūksta", "ro": "lipsește din",
    },
    "about this mirror": {
        "de": "über diesen Spiegel", "fr": "à propos de ce miroir",
        "es": "sobre este espejo", "it": "informazioni su questo mirror",
        "pt": "sobre este espelho",
        "ru": "об этом зеркале", "zh-cn": "关于此镜像", "zh-tw": "關於此鏡像",
        "ja": "このミラーについて", "cs": "o tomto zrcadle", "el": "σχετικά με αυτό το αντίγραφο",
        "lt": "apie šią kopiją", "ro": "despre această oglindă",
    },
    "advanced search": {
        "de": "erweiterte Suche", "fr": "recherche avancée",
        "es": "búsqueda avanzada", "it": "ricerca avanzata",
        "pt": "pesquisa avançada",
        "ru": "расширенный поиск", "zh-cn": "高级搜索", "zh-tw": "進階搜尋",
        "ja": "高度な検索", "cs": "rozšířené vyhledávání", "el": "σύνθετη αναζήτηση",
        "lt": "išplėstinė paieška", "ro": "căutare avansată",
    },
    "infrastructure comparison": {
        "de": "Infrastrukturvergleich", "fr": "comparaison d'infrastructure",
        "es": "comparación de infraestructura", "it": "confronto infrastruttura",
        "pt": "comparação de infraestrutura",
        "ru": "сравнение инфраструктуры", "zh-cn": "基础设施比较", "zh-tw": "基礎設施比較",
        "ja": "インフラ比較", "cs": "porovnání infrastruktury", "el": "σύγκριση υποδομής",
        "lt": "infrastruktūros palyginimas", "ro": "comparare infrastructură",
    },
    "Synced. Read Only. Fast.": {
        "de": "Synchronisiert. Nur lesbar. Schnell.",
        "fr": "Synchronisé. Lecture seule. Rapide.",
        "es": "Sincronizado. Solo lectura. Rápido.",
        "it": "Sincronizzato. Sola lettura. Veloce.",
        "pt": "Sincronizado. Somente leitura. Rápido.",
        "ru": "Синхронизировано. Только чтение. Быстро.",
        "zh-cn": "已同步。只读。快速。",
        "zh-tw": "已同步。唯讀。快速。",
        "ja": "同期済み。読み取り専用。高速。",
        "cs": "Synchronizováno. Pouze pro čtení. Rychle.",
        "el": "Συγχρονισμένο. Μόνο ανάγνωση. Γρήγορο.",
        "lt": "Sinchronizuota. Tik skaitoma. Greita.",
        "ro": "Sincronizat. Numai citire. Rapid.",
    },
    # ── Compare page ──────────────────────────────────────────────────────────
    "Compare Infrastructure": {
        "de": "Infrastruktur vergleichen", "fr": "Comparer l'infrastructure",
        "es": "Comparar infraestructura", "it": "Confronta infrastruttura",
        "pt": "Comparar infraestrutura",
        "ru": "Сравнить инфраструктуру", "zh-cn": "比较基础设施", "zh-tw": "比較基礎設施",
        "ja": "インフラを比較", "cs": "Porovnat infrastrukturu", "el": "Σύγκριση υποδομής",
        "lt": "Palyginti infrastruktūrą", "ro": "Comparare infrastructură",
    },
    "Compare page": {
        "de": "Vergleichsseite", "fr": "Page de comparaison",
        "es": "Página de comparación", "it": "Pagina di confronto",
        "pt": "Página de comparação",
        "ru": "Страница сравнения", "zh-cn": "比较页", "zh-tw": "比較頁面",
        "ja": "比較ページ", "cs": "Stránka porovnání", "el": "Σελίδα σύγκρισης",
        "lt": "Palyginimo puslapis", "ro": "Pagina de comparare",
    },
    "Compare with another entity": {
        "de": "Mit einer anderen Entität vergleichen", "fr": "Comparer avec une autre entité",
        "es": "Comparar con otra entidad", "it": "Confronta con un'altra entità",
        "pt": "Comparar com outra entidade",
        "ru": "Сравнить с другим объектом", "zh-cn": "与其他实体比较", "zh-tw": "與其他實體比較",
        "ja": "別のエンティティと比較", "cs": "Porovnat s jiným subjektem", "el": "Σύγκριση με άλλη οντότητα",
        "lt": "Palyginti su kitu subjektu", "ro": "Comparare cu altă entitate",
    },
    "Comparing entities...": {
        "de": "Entitäten werden verglichen...", "fr": "Comparaison des entités...",
        "es": "Comparando entidades...", "it": "Confronto entità...",
        "pt": "Comparando entidades...",
        "ru": "Сравнение объектов...", "zh-cn": "正在比较实体...", "zh-tw": "正在比較實體...",
        "ja": "エンティティを比較中...", "cs": "Porovnávání subjektů...", "el": "Σύγκριση οντοτήτων...",
        "lt": "Lyginami subjektai...", "ro": "Se compară entitățile...",
    },
    "New comparison": {
        "de": "Neuer Vergleich", "fr": "Nouvelle comparaison",
        "es": "Nueva comparación", "it": "Nuovo confronto",
        "pt": "Nova comparação",
        "ru": "Новое сравнение", "zh-cn": "新对比", "zh-tw": "新比較",
        "ja": "新規比較", "cs": "Nové porovnání", "el": "Νέα σύγκριση",
        "lt": "Naujas palyginimas", "ro": "Comparare nouă",
    },
    "Shared IXPs": {
        "de": "Gemeinsame IXPs", "fr": "IXPs communs",
        "es": "IXPs compartidos", "it": "IXP condivisi",
        "pt": "IXPs partilhados",
        "ru": "Общие IXP", "zh-cn": "共同互联网交换点", "zh-tw": "共同網際網路交換點",
        "ja": "共有IXP", "cs": "Sdílené IXP", "el": "Κοινά IXP",
        "lt": "Bendri IXP", "ro": "IXP-uri partajate",
    },
    "Shared Facilities": {
        "de": "Gemeinsame Einrichtungen", "fr": "Installations communes",
        "es": "Instalaciones compartidas", "it": "Strutture condivise",
        "pt": "Instalações partilhadas",
        "ru": "Общие объекты", "zh-cn": "共用设施", "zh-tw": "共用設施",
        "ja": "共有ファシリティ", "cs": "Sdílené objekty", "el": "Κοινές εγκαταστάσεις",
        "lt": "Bendros patalpos", "ro": "Facilități partajate",
    },
    "Shared Networks": {
        "de": "Gemeinsame Netzwerke", "fr": "Réseaux communs",
        "es": "Redes compartidas", "it": "Reti condivise",
        "pt": "Redes partilhadas",
        "ru": "Общие сети", "zh-cn": "共享网络", "zh-tw": "共享網路",
        "ja": "共有ネットワーク", "cs": "Sdílené sítě", "el": "Κοινά δίκτυα",
        "lt": "Bendri tinklai", "ro": "Rețele partajate",
    },
    "IXPs": {
        "de": "IXPs", "fr": "IXPs", "es": "IXPs",
        "it": "IXP", "pt": "IXPs",
        "ru": "IXP", "zh-cn": "互联网交换点", "zh-tw": "網際網路交換點",
        "ja": "IXP", "cs": "IXP", "el": "IXP",
        "lt": "IXP", "ro": "IXP-uri",
    },
    "IXPs at": {
        "de": "IXPs bei", "fr": "IXPs à", "es": "IXPs en",
        "it": "IXP a", "pt": "IXPs em",
        "ru": "IXP в", "zh-cn": "位于…的IXP", "zh-tw": "位於…的IXP",
        "ja": "…のIXP", "cs": "IXP v", "el": "IXP στο",
        "lt": "IXP ties", "ro": "IXP-uri la",
    },
    "IXPs only at": {
        "de": "IXPs nur bei", "fr": "IXPs uniquement à", "es": "IXPs solo en",
        "it": "IXP solo a", "pt": "IXPs apenas em",
        "ru": "IXP только в", "zh-cn": "仅在…的IXP", "zh-tw": "僅在…的IXP",
        "ja": "…のみのIXP", "cs": "IXP pouze v", "el": "IXP μόνο στο",
        "lt": "IXP tik ties", "ro": "IXP-uri numai la",
    },
    "IXPs in facility {fac} that {net} peers at": {
        "de": "IXPs in Einrichtung {fac}, bei denen {net} peert",
        "fr": "IXPs dans l'installation {fac} où {net} paire",
        "es": "IXPs en la instalación {fac} donde {net} hace peering",
        "it": "IXP nella struttura {fac} dove {net} fa peering",
        "pt": "IXPs na instalação {fac} onde {net} tem peering",
        "ru": "IXP в объекте {fac}, где пирит {net}",
        "zh-cn": "{fac}设施中{net}进行对等的IXP",
        "zh-tw": "{fac}設施中{net}進行對等的IXP",
        "ja": "{fac}施設内で{net}がピアリングするIXP",
        "cs": "IXP v objektu {fac}, kde {net} peeruje",
        "el": "IXP στη {fac} όπου κάνει peering το {net}",
        "lt": "IXP patalpose {fac}, kur {net} jungiasi",
        "ro": "IXP-uri în facilitatea {fac} unde {net} face peering",
    },
    "Networks at": {
        "de": "Netzwerke bei", "fr": "Réseaux à", "es": "Redes en",
        "it": "Reti a", "pt": "Redes em",
        "ru": "Сети в", "zh-cn": "位于…的网络", "zh-tw": "位於…的網路",
        "ja": "…のネットワーク", "cs": "Sítě v", "el": "Δίκτυα στο",
        "lt": "Tinklai ties", "ro": "Rețele la",
    },
    "Networks only at": {
        "de": "Netzwerke nur bei", "fr": "Réseaux uniquement à", "es": "Redes solo en",
        "it": "Reti solo a", "pt": "Redes apenas em",
        "ru": "Сети только в", "zh-cn": "仅在…的网络", "zh-tw": "僅在…的網路",
        "ja": "…のみのネットワーク", "cs": "Sítě pouze v", "el": "Δίκτυα μόνο στο",
        "lt": "Tinklai tik ties", "ro": "Rețele numai la",
    },
    "Networks in facility {fac} peering at {ix}": {
        "de": "Netzwerke in Einrichtung {fac}, die bei {ix} peern",
        "fr": "Réseaux dans l'installation {fac} pairant à {ix}",
        "es": "Redes en la instalación {fac} haciendo peering en {ix}",
        "it": "Reti nella struttura {fac} che fanno peering a {ix}",
        "pt": "Redes na instalação {fac} com peering em {ix}",
        "ru": "Сети в объекте {fac}, пирящие в {ix}",
        "zh-cn": "{fac}设施中在{ix}进行对等的网络",
        "zh-tw": "{fac}設施中在{ix}進行對等的網路",
        "ja": "{fac}施設内で{ix}にピアリングするネットワーク",
        "cs": "Sítě v objektu {fac} peerující v {ix}",
        "el": "Δίκτυα στη {fac} με peering στο {ix}",
        "lt": "Tinklai patalpose {fac}, besijungiantys prie {ix}",
        "ro": "Rețele în facilitatea {fac} care fac peering la {ix}",
    },
    "Facilities only at": {
        "de": "Einrichtungen nur bei", "fr": "Installations uniquement à",
        "es": "Instalaciones solo en", "it": "Strutture solo a",
        "pt": "Instalações apenas em",
        "ru": "Объекты только в", "zh-cn": "仅在…的设施", "zh-tw": "僅在…的設施",
        "ja": "…のみの施設", "cs": "Objekty pouze v", "el": "Εγκαταστάσεις μόνο στο",
        "lt": "Patalpos tik ties", "ro": "Facilități numai la",
    },
    "Connections to IXPs": {
        "de": "Verbindungen zu IXPs", "fr": "Connexions aux IXPs",
        "es": "Conexiones a IXPs", "it": "Connessioni agli IXP",
        "pt": "Ligações a IXPs",
        "ru": "Подключения к IXP", "zh-cn": "到IXP的连接", "zh-tw": "到IXP的連線",
        "ja": "IXPへの接続", "cs": "Připojení k IXP", "el": "Συνδέσεις σε IXP",
        "lt": "Ryšiai su IXP", "ro": "Conexiuni la IXP-uri",
    },
    "NOT at": {
        "de": "NICHT bei", "fr": "PAS à", "es": "NO en",
        "it": "NON a", "pt": "NÃO em",
        "ru": "НЕ в", "zh-cn": "不在…", "zh-tw": "不在…",
        "ja": "…にはなし", "cs": "NENÍ v", "el": "ΌΧΙ στο",
        "lt": "NE ties", "ro": "NU la",
    },
    "peers at that are NOT at": {
        "de": "peert bei, aber NICHT bei", "fr": "paire à, mais PAS à",
        "es": "hace peering en, pero NO en", "it": "fa peering a, ma NON a",
        "pt": "faz peering em, mas NÃO em",
        "ru": "пирит в, но НЕ в", "zh-cn": "在…对等但不在…", "zh-tw": "在…對等但不在…",
        "ja": "…でピアリングするが…にはなし", "cs": "peeruje v, ale NENÍ v",
        "el": "κάνει peering αλλά ΌΧΙ στο", "lt": "jungiasi ties, bet NE ties",
        "ro": "face peering la dar NU la",
    },
    "{count} results": {
        "de": "{count} Ergebnisse", "fr": "{count} résultats", "es": "{count} resultados",
        "it": "{count} risultati", "pt": "{count} resultados",
        "ru": "{count} результатов", "zh-cn": "{count} 个结果", "zh-tw": "{count} 個結果",
        "ja": "{count}件の結果", "cs": "{count} výsledků", "el": "{count} αποτελέσματα",
        "lt": "{count} rezultatai", "ro": "{count} rezultate",
    },
    "{n} favorites": {
        "de": "{n} Favoriten", "fr": "{n} favoris", "es": "{n} favoritos",
        "it": "{n} preferiti", "pt": "{n} favoritos",
        "ru": "{n} в избранном", "zh-cn": "{n} 个收藏", "zh-tw": "{n} 個我的最愛",
        "ja": "{n}件のお気に入り", "cs": "{n} oblíbených", "el": "{n} αγαπημένα",
        "lt": "{n} mėgstami", "ro": "{n} favorite",
    },
    "Speed A": {
        "de": "Geschwindigkeit A", "fr": "Vitesse A", "es": "Velocidad A",
        "it": "Velocità A", "pt": "Velocidade A",
        "ru": "Скорость A", "zh-cn": "速度 A", "zh-tw": "速度 A",
        "ja": "速度 A", "cs": "Rychlost A", "el": "Ταχύτητα Α",
        "lt": "Greitis A", "ro": "Viteză A",
    },
    "Speed B": {
        "de": "Geschwindigkeit B", "fr": "Vitesse B", "es": "Velocidad B",
        "it": "Velocità B", "pt": "Velocidade B",
        "ru": "Скорость B", "zh-cn": "速度 B", "zh-tw": "速度 B",
        "ja": "速度 B", "cs": "Rychlost B", "el": "Ταχύτητα Β",
        "lt": "Greitis B", "ro": "Viteză B",
    },
    "IPv4 A": {"*": "IPv4 A"},
    "IPv4 B": {"*": "IPv4 B"},
    "IP Address": {
        "de": "IP-Adresse", "fr": "Adresse IP", "es": "Dirección IP",
        "it": "Indirizzo IP", "pt": "Endereço IP",
        "ru": "IP-адрес", "zh-cn": "IP地址", "zh-tw": "IP位址",
        "ja": "IPアドレス", "cs": "IP adresa", "el": "Διεύθυνση IP",
        "lt": "IP adresas", "ro": "Adresă IP",
    },
    # ── Favorites ─────────────────────────────────────────────────────────────
    "Your Favorites": {
        "de": "Ihre Favoriten", "fr": "Vos favoris", "es": "Sus favoritos",
        "it": "I tuoi preferiti", "pt": "Os seus favoritos",
        "ru": "Ваше избранное", "zh-cn": "您的收藏", "zh-tw": "您的我的最愛",
        "ja": "お気に入り", "cs": "Vaše oblíbené", "el": "Τα αγαπημένα σας",
        "lt": "Jūsų mėgstami", "ro": "Favoritele dvs.",
    },
    "Add to favorites": {
        "de": "Zu Favoriten hinzufügen", "fr": "Ajouter aux favoris",
        "es": "Añadir a favoritos", "it": "Aggiungi ai preferiti",
        "pt": "Adicionar aos favoritos",
        "ru": "Добавить в избранное", "zh-cn": "添加到收藏夹", "zh-tw": "加入我的最愛",
        "ja": "お気に入りに追加", "cs": "Přidat do oblíbených", "el": "Προσθήκη στα αγαπημένα",
        "lt": "Pridėti prie mėgstamų", "ro": "Adăugare la favorite",
    },
    "Remove from favorites": {
        "de": "Aus Favoriten entfernen", "fr": "Supprimer des favoris",
        "es": "Eliminar de favoritos", "it": "Rimuovi dai preferiti",
        "pt": "Remover dos favoritos",
        "ru": "Удалить из избранного", "zh-cn": "从收藏夹中删除", "zh-tw": "從我的最愛中移除",
        "ja": "お気に入りから削除", "cs": "Odebrat z oblíbených", "el": "Αφαίρεση από αγαπημένα",
        "lt": "Pašalinti iš mėgstamų", "ro": "Eliminare din favorite",
    },
    "No favorites yet": {
        "de": "Noch keine Favoriten", "fr": "Pas encore de favoris",
        "es": "Aún no hay favoritos", "it": "Nessun preferito ancora",
        "pt": "Ainda não há favoritos",
        "ru": "Пока нет избранного", "zh-cn": "还没有收藏", "zh-tw": "尚無我的最愛",
        "ja": "まだお気に入りはありません", "cs": "Zatím žádné oblíbené", "el": "Δεν υπάρχουν αγαπημένα ακόμα",
        "lt": "Dar nėra mėgstamų", "ro": "Niciun favorit încă",
    },
    "No favorites yet. Use the star button on any entity page to add favorites.": {
        "de": "Noch keine Favoriten. Verwenden Sie den Stern auf einer Entitätsseite, um Favoriten hinzuzufügen.",
        "fr": "Pas encore de favoris. Utilisez le bouton étoile sur n'importe quelle page d'entité pour ajouter des favoris.",
        "es": "Aún no hay favoritos. Use el botón de estrella en cualquier página de entidad para añadir favoritos.",
        "it": "Nessun preferito ancora. Usa il pulsante stella su qualsiasi pagina entità per aggiungere preferiti.",
        "pt": "Ainda não há favoritos. Use o botão de estrela em qualquer página de entidade para adicionar favoritos.",
        "ru": "Пока нет избранного. Используйте звёздочку на любой странице объекта, чтобы добавить в избранное.",
        "zh-cn": "还没有收藏。在任何实体页面上使用星形按钮添加收藏。",
        "zh-tw": "尚無我的最愛。在任何實體頁面上使用星形按鈕加入我的最愛。",
        "ja": "まだお気に入りはありません。エンティティページの星ボタンでお気に入りに追加できます。",
        "cs": "Zatím žádné oblíbené. Použijte tlačítko hvězdičky na stránce libovolného subjektu pro přidání do oblíbených.",
        "el": "Δεν υπάρχουν αγαπημένα ακόμα. Χρησιμοποιήστε το κουμπί αστεριού σε οποιαδήποτε σελίδα οντότητας.",
        "lt": "Dar nėra mėgstamų. Naudokite žvaigždutės mygtuką bet kuriame objekto puslapyje.",
        "ro": "Niciun favorit încă. Folosiți butonul stea pe orice pagină de entitate pentru a adăuga favorite.",
    },
    "Use the ★ on any entity page to add favorites.": {
        "de": "Verwenden Sie ★ auf einer Entitätsseite, um Favoriten hinzuzufügen.",
        "fr": "Utilisez ★ sur n'importe quelle page d'entité pour ajouter des favoris.",
        "es": "Use ★ en cualquier página de entidad para añadir favoritos.",
        "it": "Usa ★ su qualsiasi pagina entità per aggiungere preferiti.",
        "pt": "Use ★ em qualquer página de entidade para adicionar favoritos.",
        "ru": "Используйте ★ на любой странице объекта, чтобы добавить в избранное.",
        "zh-cn": "在任何实体页面使用 ★ 添加收藏。",
        "zh-tw": "在任何實體頁面使用 ★ 加入我的最愛。",
        "ja": "エンティティページで ★ を使ってお気に入りに追加。",
        "cs": "Použijte ★ na libovolné stránce subjektu pro přidání do oblíbených.",
        "el": "Χρησιμοποιήστε ★ σε οποιαδήποτε σελίδα οντότητας για να προσθέσετε αγαπημένα.",
        "lt": "Naudokite ★ bet kuriame objekto puslapyje, kad pridėtumėte prie mėgstamų.",
        "ro": "Folosiți ★ pe orice pagină de entitate pentru a adăuga la favorite.",
    },
    "Use the ★ button on any network, exchange, or facility page to add it here.": {
        "de": "Verwenden Sie ★ auf einer Netzwerk-, Austauschpunkt- oder Einrichtungsseite, um es hier hinzuzufügen.",
        "fr": "Utilisez ★ sur n'importe quelle page de réseau, échange ou installation pour l'ajouter ici.",
        "es": "Use ★ en cualquier página de red, intercambio o instalación para añadirlo aquí.",
        "it": "Usa ★ su qualsiasi pagina di rete, scambio o struttura per aggiungerla qui.",
        "pt": "Use ★ em qualquer página de rede, troca ou instalação para adicioná-la aqui.",
        "ru": "Используйте ★ на странице сети, точки обмена или объекта, чтобы добавить его сюда.",
        "zh-cn": "在任何网络、交换或设施页面使用 ★ 将其添加到此处。",
        "zh-tw": "在任何網路、交換或設施頁面使用 ★ 將其加入此處。",
        "ja": "ネットワーク、交換所、施設の各ページで ★ を使ってここに追加。",
        "cs": "Použijte ★ na stránce libovolné sítě, výměny nebo objektu pro přidání sem.",
        "el": "Χρησιμοποιήστε ★ σε σελίδα δικτύου, ανταλλαγής ή εγκατάστασης για προσθήκη εδώ.",
        "lt": "Naudokite ★ bet kuriame tinklo, mainų ar objekto puslapyje, kad pridėtumėte čia.",
        "ro": "Folosiți ★ pe orice pagină de rețea, schimb sau facilitate pentru a adăuga aici.",
    },
    "Drag to reorder": {
        "de": "Zum Umsortieren ziehen", "fr": "Faire glisser pour réorganiser",
        "es": "Arrastrar para reordenar", "it": "Trascina per riordinare",
        "pt": "Arraste para reordenar",
        "ru": "Перетащите для сортировки", "zh-cn": "拖动以重新排序", "zh-tw": "拖曳以重新排序",
        "ja": "ドラッグして並べ替え", "cs": "Přetáhnout pro přeřazení", "el": "Σύρετε για αναδιάταξη",
        "lt": "Vilkti norėdami pertvarkyti", "ro": "Trageți pentru reordonare",
    },
    "Drag to reorder. Use the star button on any entity page to add favorites.": {
        "de": "Zum Umsortieren ziehen. Verwenden Sie den Stern auf einer Entitätsseite, um Favoriten hinzuzufügen.",
        "fr": "Faire glisser pour réorganiser. Utilisez le bouton étoile sur n'importe quelle page d'entité.",
        "es": "Arrastrar para reordenar. Use el botón de estrella en cualquier página de entidad.",
        "it": "Trascina per riordinare. Usa il pulsante stella su qualsiasi pagina entità.",
        "pt": "Arraste para reordenar. Use o botão de estrela em qualquer página de entidade.",
        "ru": "Перетащите для сортировки. Используйте звёздочку на странице объекта.",
        "zh-cn": "拖动以重新排序。在任何实体页面使用星形按钮添加收藏。",
        "zh-tw": "拖曳以重新排序。在任何實體頁面使用星形按鈕加入我的最愛。",
        "ja": "ドラッグして並べ替え。エンティティページの星ボタンでお気に入りに追加。",
        "cs": "Přetáhnout pro přeřazení. Použijte hvězdičku na stránce subjektu.",
        "el": "Σύρετε για αναδιάταξη. Χρησιμοποιήστε το αστέρι σε σελίδα οντότητας.",
        "lt": "Vilkti norėdami pertvarkyti. Naudokite žvaigždutę bet kuriame objekto puslapyje.",
        "ro": "Trageți pentru reordonare. Folosiți butonul stea pe orice pagină de entitate.",
    },
    "View all in Account": {
        "de": "Alle im Konto anzeigen", "fr": "Tout voir dans le compte",
        "es": "Ver todo en la cuenta", "it": "Visualizza tutto nell'account",
        "pt": "Ver tudo na conta",
        "ru": "Показать всё в аккаунте", "zh-cn": "在账户中查看全部", "zh-tw": "在帳戶中查看全部",
        "ja": "アカウントで全件表示", "cs": "Zobrazit vše v účtu", "el": "Εμφάνιση όλων στον λογαριασμό",
        "lt": "Žiūrėti visus paskyroje", "ro": "Vezi toate în cont",
    },
    "My Stuff": {
        "de": "Meine Sachen", "fr": "Mes ressources", "es": "Mis recursos",
        "it": "Le mie risorse", "pt": "Os meus recursos",
        "ru": "Мои ресурсы", "zh-cn": "我的资源", "zh-tw": "我的資源",
        "ja": "マイリソース", "cs": "Moje věci", "el": "Τα δικά μου",
        "lt": "Mano ištekliai", "ro": "Resursele mele",
    },
    "My Affiliations": {
        "de": "Meine Zugehörigkeiten", "fr": "Mes affiliations",
        "es": "Mis afiliaciones", "it": "Le mie affiliazioni",
        "pt": "As minhas afiliações",
        "ru": "Мои аффилиации", "zh-cn": "我的关联", "zh-tw": "我的關聯",
        "ja": "マイアフィリエーション", "cs": "Moje příslušnosti", "el": "Οι συνδέσεις μου",
        "lt": "Mano priklausomybės", "ro": "Afilierile mele",
    },
    # ── Error / status messages ───────────────────────────────────────────────
    "Network {id} not found": {
        "de": "Netzwerk {id} nicht gefunden", "fr": "Réseau {id} introuvable",
        "es": "Red {id} no encontrada", "it": "Rete {id} non trovata",
        "pt": "Rede {id} não encontrada",
        "ru": "Сеть {id} не найдена", "zh-cn": "未找到网络 {id}", "zh-tw": "找不到網路 {id}",
        "ja": "ネットワーク {id} が見つかりません", "cs": "Síť {id} nenalezena", "el": "Το δίκτυο {id} δεν βρέθηκε",
        "lt": "Tinklas {id} nerastas", "ro": "Rețeaua {id} nu a fost găsită",
    },
    "Exchange {id} not found": {
        "de": "Austauschpunkt {id} nicht gefunden", "fr": "Échange {id} introuvable",
        "es": "Intercambio {id} no encontrado", "it": "Scambio {id} non trovato",
        "pt": "Troca {id} não encontrada",
        "ru": "Точка обмена {id} не найдена", "zh-cn": "未找到交换点 {id}", "zh-tw": "找不到交換點 {id}",
        "ja": "IXP {id} が見つかりません", "cs": "Výměna {id} nenalezena", "el": "Η ανταλλαγή {id} δεν βρέθηκε",
        "lt": "Mainų taškas {id} nerastas", "ro": "Schimbul {id} nu a fost găsit",
    },
    "Facility {id} not found": {
        "de": "Einrichtung {id} nicht gefunden", "fr": "Installation {id} introuvable",
        "es": "Instalación {id} no encontrada", "it": "Struttura {id} non trovata",
        "pt": "Instalação {id} não encontrada",
        "ru": "Объект {id} не найден", "zh-cn": "未找到设施 {id}", "zh-tw": "找不到設施 {id}",
        "ja": "施設 {id} が見つかりません", "cs": "Objekt {id} nenalezen", "el": "Η εγκατάσταση {id} δεν βρέθηκε",
        "lt": "Pastatas {id} nerastas", "ro": "Facilitatea {id} nu a fost găsită",
    },
    "Campus {id} not found": {
        "de": "Campus {id} nicht gefunden", "fr": "Campus {id} introuvable",
        "es": "Campus {id} no encontrado", "it": "Campus {id} non trovato",
        "pt": "Campus {id} não encontrado",
        "ru": "Кампус {id} не найден", "zh-cn": "未找到园区 {id}", "zh-tw": "找不到校園 {id}",
        "ja": "キャンパス {id} が見つかりません", "cs": "Kampus {id} nenalezen", "el": "Το campus {id} δεν βρέθηκε",
        "lt": "Miestelis {id} nerastas", "ro": "Campusul {id} nu a fost găsit",
    },
    "Carrier {id} not found": {
        "de": "Carrier {id} nicht gefunden", "fr": "Opérateur {id} introuvable",
        "es": "Operador {id} no encontrado", "it": "Operatore {id} non trovato",
        "pt": "Operador {id} não encontrado",
        "ru": "Оператор {id} не найден", "zh-cn": "未找到运营商 {id}", "zh-tw": "找不到電信業者 {id}",
        "ja": "キャリア {id} が見つかりません", "cs": "Operátor {id} nenalezen", "el": "Ο carrier {id} δεν βρέθηκε",
        "lt": "Operatorius {id} nerastas", "ro": "Operatorul {id} nu a fost găsit",
    },
    "Organization {id} not found": {
        "de": "Organisation {id} nicht gefunden", "fr": "Organisation {id} introuvable",
        "es": "Organización {id} no encontrada", "it": "Organizzazione {id} non trovata",
        "pt": "Organização {id} não encontrada",
        "ru": "Организация {id} не найдена", "zh-cn": "未找到组织 {id}", "zh-tw": "找不到組織 {id}",
        "ja": "組織 {id} が見つかりません", "cs": "Organizace {id} nenalezena", "el": "Ο οργανισμός {id} δεν βρέθηκε",
        "lt": "Organizacija {id} nerasta", "ro": "Organizația {id} nu a fost găsită",
    },
    "Invalid ASN: {asn}": {
        "de": "Ungültige ASN: {asn}", "fr": "ASN invalide : {asn}",
        "es": "ASN no válido: {asn}", "it": "ASN non valido: {asn}",
        "pt": "ASN inválido: {asn}",
        "ru": "Неверный ASN: {asn}", "zh-cn": "无效ASN：{asn}", "zh-tw": "無效的ASN：{asn}",
        "ja": "無効なASN：{asn}", "cs": "Neplatný ASN: {asn}", "el": "Μη έγκυρο ASN: {asn}",
        "lt": "Netinkamas ASN: {asn}", "ro": "ASN invalid: {asn}",
    },
    "Looking up AS{asn}": {
        "de": "AS{asn} wird gesucht", "fr": "Recherche de AS{asn}",
        "es": "Buscando AS{asn}", "it": "Ricerca di AS{asn}",
        "pt": "A procurar AS{asn}",
        "ru": "Поиск AS{asn}", "zh-cn": "正在查找 AS{asn}", "zh-tw": "正在查找 AS{asn}",
        "ja": "AS{asn} を検索中", "cs": "Vyhledávání AS{asn}", "el": "Αναζήτηση AS{asn}",
        "lt": "Ieškoma AS{asn}", "ro": "Se caută AS{asn}",
    },
    "No network found for AS{asn}": {
        "de": "Kein Netzwerk für AS{asn} gefunden", "fr": "Aucun réseau trouvé pour AS{asn}",
        "es": "No se encontró red para AS{asn}", "it": "Nessuna rete trovata per AS{asn}",
        "pt": "Nenhuma rede encontrada para AS{asn}",
        "ru": "Сеть для AS{asn} не найдена", "zh-cn": "未找到AS{asn}的网络", "zh-tw": "找不到 AS{asn} 的網路",
        "ja": "AS{asn} のネットワークが見つかりません", "cs": "Pro AS{asn} nebyla nalezena žádná síť",
        "el": "Δεν βρέθηκε δίκτυο για AS{asn}", "lt": "AS{asn} tinklas nerastas",
        "ro": "Nu s-a găsit nicio rețea pentru AS{asn}",
    },
    "No results found. Try broader search criteria.": {
        "de": "Keine Ergebnisse gefunden. Versuchen Sie breitere Suchkriterien.",
        "fr": "Aucun résultat. Essayez des critères de recherche plus larges.",
        "es": "No se encontraron resultados. Pruebe criterios de búsqueda más amplios.",
        "it": "Nessun risultato trovato. Prova criteri di ricerca più ampi.",
        "pt": "Nenhum resultado encontrado. Tente critérios de pesquisa mais amplos.",
        "ru": "Результаты не найдены. Попробуйте расширить критерии поиска.",
        "zh-cn": "未找到结果。请尝试更广泛的搜索条件。",
        "zh-tw": "未找到結果。請嘗試更廣泛的搜尋條件。",
        "ja": "結果が見つかりませんでした。より広い検索条件をお試しください。",
        "cs": "Nenalezeny žádné výsledky. Zkuste širší vyhledávací kritéria.",
        "el": "Δεν βρέθηκαν αποτελέσματα. Δοκιμάστε ευρύτερα κριτήρια αναζήτησης.",
        "lt": "Rezultatų nerasta. Pamėginkite platesnius paieškos kriterijus.",
        "ro": "Nu s-au găsit rezultate. Încercați criterii de căutare mai largi.",
    },
    "Not found in PeeringDB": {
        "de": "Nicht in PeeringDB gefunden", "fr": "Introuvable dans PeeringDB",
        "es": "No encontrado en PeeringDB", "it": "Non trovato in PeeringDB",
        "pt": "Não encontrado no PeeringDB",
        "ru": "Не найдено в PeeringDB", "zh-cn": "在PeeringDB中未找到", "zh-tw": "在PeeringDB中找不到",
        "ja": "PeeringDBに見つかりません", "cs": "Nenalezeno v PeeringDB", "el": "Δεν βρέθηκε στο PeeringDB",
        "lt": "PeeringDB nerasta", "ro": "Nu a fost găsit în PeeringDB",
    },
    "No affiliations found.": {
        "de": "Keine Zugehörigkeiten gefunden.", "fr": "Aucune affiliation trouvée.",
        "es": "No se encontraron afiliaciones.", "it": "Nessuna affiliazione trovata.",
        "pt": "Nenhuma afiliação encontrada.",
        "ru": "Аффилиации не найдены.", "zh-cn": "未找到关联。", "zh-tw": "找不到關聯。",
        "ja": "アフィリエーションが見つかりません。", "cs": "Žádné příslušnosti nenalezeny.",
        "el": "Δεν βρέθηκαν συνδέσεις.", "lt": "Priklausomybių nerasta.",
        "ro": "Nu s-au găsit afilieri.",
    },
    "No network affiliations.": {
        "de": "Keine Netzwerkzugehörigkeiten.", "fr": "Aucune affiliation réseau.",
        "es": "Sin afiliaciones de red.", "it": "Nessuna affiliazione di rete.",
        "pt": "Sem afiliações de rede.",
        "ru": "Нет сетевых аффилиаций.", "zh-cn": "没有网络关联。", "zh-tw": "沒有網路關聯。",
        "ja": "ネットワークアフィリエーションはありません。", "cs": "Žádné síťové příslušnosti.",
        "el": "Δεν υπάρχουν συνδέσεις δικτύου.", "lt": "Nėra tinklo priklausomybių.",
        "ro": "Nicio afiliere de rețea.",
    },
    "No entities": {
        "de": "Keine Entitäten", "fr": "Aucune entité", "es": "Sin entidades",
        "it": "Nessuna entità", "pt": "Sem entidades",
        "ru": "Нет объектов", "zh-cn": "无实体", "zh-tw": "無實體",
        "ja": "エンティティなし", "cs": "Žádné subjekty", "el": "Καμία οντότητα",
        "lt": "Nėra subjektų", "ro": "Nicio entitate",
    },
    "No matches": {
        "de": "Keine Treffer", "fr": "Aucune correspondance", "es": "Sin coincidencias",
        "it": "Nessuna corrispondenza", "pt": "Sem correspondências",
        "ru": "Нет совпадений", "zh-cn": "无匹配", "zh-tw": "無符合項目",
        "ja": "一致なし", "cs": "Žádné shody", "el": "Δεν βρέθηκαν αποτελέσματα",
        "lt": "Atitikmenų nerasta", "ro": "Nicio potrivire",
    },
    "No shared infrastructure found between these exchanges.": {
        "de": "Keine gemeinsame Infrastruktur zwischen diesen Austauschpunkten gefunden.",
        "fr": "Aucune infrastructure commune trouvée entre ces échanges.",
        "es": "No se encontró infraestructura compartida entre estos intercambios.",
        "it": "Nessuna infrastruttura condivisa trovata tra questi scambi.",
        "pt": "Nenhuma infraestrutura partilhada encontrada entre estas trocas.",
        "ru": "Общая инфраструктура между этими точками обмена не найдена.",
        "zh-cn": "这些交换点之间未发现共享基础设施。",
        "zh-tw": "這些交換點之間未發現共享基礎設施。",
        "ja": "これらの交換所間に共有インフラは見つかりませんでした。",
        "cs": "Mezi těmito výměnami nebyla nalezena žádná sdílená infrastruktura.",
        "el": "Δεν βρέθηκε κοινή υποδομή μεταξύ αυτών των ανταλλαγών.",
        "lt": "Tarp šių mainų taškų nerasta bendros infrastruktūros.",
        "ro": "Nu s-a găsit infrastructură partajată între aceste schimburi.",
    },
    "No shared infrastructure found between these networks.": {
        "de": "Keine gemeinsame Infrastruktur zwischen diesen Netzwerken gefunden.",
        "fr": "Aucune infrastructure commune trouvée entre ces réseaux.",
        "es": "No se encontró infraestructura compartida entre estas redes.",
        "it": "Nessuna infrastruttura condivisa trovata tra queste reti.",
        "pt": "Nenhuma infraestrutura partilhada encontrada entre estas redes.",
        "ru": "Общая инфраструктура между этими сетями не найдена.",
        "zh-cn": "这些网络之间未发现共享基础设施。",
        "zh-tw": "這些網路之間未發現共享基礎設施。",
        "ja": "これらのネットワーク間に共有インフラは見つかりませんでした。",
        "cs": "Mezi těmito sítěmi nebyla nalezena žádná sdílená infrastruktura.",
        "el": "Δεν βρέθηκε κοινή υποδομή μεταξύ αυτών των δικτύων.",
        "lt": "Tarp šių tinklų nerasta bendros infrastruktūros.",
        "ro": "Nu s-a găsit infrastructură partajată între aceste rețele.",
    },
    "No shared topology found between these facilities.": {
        "de": "Keine gemeinsame Topologie zwischen diesen Einrichtungen gefunden.",
        "fr": "Aucune topologie commune trouvée entre ces installations.",
        "es": "No se encontró topología compartida entre estas instalaciones.",
        "it": "Nessuna topologia condivisa trovata tra queste strutture.",
        "pt": "Nenhuma topologia partilhada encontrada entre estas instalações.",
        "ru": "Общая топология между этими объектами не найдена.",
        "zh-cn": "这些设施之间未发现共享拓扑。",
        "zh-tw": "這些設施之間未發現共享拓撲。",
        "ja": "これらの施設間に共有トポロジは見つかりませんでした。",
        "cs": "Mezi těmito objekty nebyla nalezena žádná sdílená topologie.",
        "el": "Δεν βρέθηκε κοινή τοπολογία μεταξύ αυτών των εγκαταστάσεων.",
        "lt": "Tarp šių pastatų nerasta bendros topologijos.",
        "ro": "Nu s-a găsit topologie partajată între aceste facilități.",
    },
    "Failed to load affiliations.": {
        "de": "Zugehörigkeiten konnten nicht geladen werden.", "fr": "Impossible de charger les affiliations.",
        "es": "No se pudieron cargar las afiliaciones.", "it": "Caricamento affiliazioni non riuscito.",
        "pt": "Falha ao carregar afiliações.",
        "ru": "Не удалось загрузить аффилиации.", "zh-cn": "无法加载关联。", "zh-tw": "無法載入關聯。",
        "ja": "アフィリエーションを読み込めませんでした。", "cs": "Příslušnosti nelze načíst.",
        "el": "Αδυναμία φόρτωσης συνδέσεων.", "lt": "Nepavyko įkelti priklausomybių.",
        "ro": "Imposibil de încărcat afilierile.",
    },
    "Search failed: {error}": {
        "de": "Suche fehlgeschlagen: {error}", "fr": "Recherche échouée : {error}",
        "es": "Búsqueda fallida: {error}", "it": "Ricerca fallita: {error}",
        "pt": "Pesquisa falhou: {error}",
        "ru": "Ошибка поиска: {error}", "zh-cn": "搜索失败：{error}", "zh-tw": "搜尋失敗：{error}",
        "ja": "検索に失敗しました：{error}", "cs": "Vyhledávání selhalo: {error}", "el": "Αποτυχία αναζήτησης: {error}",
        "lt": "Paieška nepavyko: {error}", "ro": "Căutare eșuată: {error}",
    },
    "ASN verification failed: {error}": {
        "de": "ASN-Verifizierung fehlgeschlagen: {error}", "fr": "Vérification ASN échouée : {error}",
        "es": "Verificación ASN fallida: {error}", "it": "Verifica ASN fallita: {error}",
        "pt": "Verificação ASN falhou: {error}",
        "ru": "Проверка ASN не удалась: {error}", "zh-cn": "ASN验证失败：{error}", "zh-tw": "ASN驗證失敗：{error}",
        "ja": "ASN検証に失敗：{error}", "cs": "Ověření ASN selhalo: {error}", "el": "Αποτυχία επαλήθευσης ASN: {error}",
        "lt": "ASN patikrinimas nepavyko: {error}", "ro": "Verificarea ASN a eșuat: {error}",
    },
    "{found} of {total} ASNs registered in PeeringDB.": {
        "de": "{found} von {total} ASNs in PeeringDB registriert.",
        "fr": "{found} sur {total} ASN enregistrés dans PeeringDB.",
        "es": "{found} de {total} ASNs registrados en PeeringDB.",
        "it": "{found} di {total} ASN registrati in PeeringDB.",
        "pt": "{found} de {total} ASNs registados no PeeringDB.",
        "ru": "{found} из {total} ASN зарегистрированы в PeeringDB.",
        "zh-cn": "PeeringDB中已注册 {found}/{total} 个ASN。",
        "zh-tw": "PeeringDB中已註冊 {found}/{total} 個ASN。",
        "ja": "PeeringDBに {found}/{total} 件のASNが登録されています。",
        "cs": "{found} z {total} ASN registrováno v PeeringDB.",
        "el": "{found} από {total} ASN εγγεγραμμένα στο PeeringDB.",
        "lt": "{found} iš {total} ASN registruoti PeeringDB.",
        "ro": "{found} din {total} ASN-uri înregistrate în PeeringDB.",
    },
    "{net} is NOT currently peering at {ix}.": {
        "de": "{net} peert derzeit NICHT bei {ix}.",
        "fr": "{net} ne paire PAS actuellement à {ix}.",
        "es": "{net} NO está actualmente haciendo peering en {ix}.",
        "it": "{net} NON sta attualmente facendo peering a {ix}.",
        "pt": "{net} NÃO está atualmente a fazer peering em {ix}.",
        "ru": "{net} в настоящее время НЕ пирит в {ix}.",
        "zh-cn": "{net} 目前未在 {ix} 进行对等。",
        "zh-tw": "{net} 目前未在 {ix} 進行對等。",
        "ja": "{net} は現在 {ix} でピアリングしていません。",
        "cs": "{net} v současné době NEPEERUJE v {ix}.",
        "el": "Το {net} δεν κάνει peering στο {ix} αυτήν τη στιγμή.",
        "lt": "{net} šiuo metu NESIJUNGIA prie {ix}.",
        "ro": "{net} NU face în prezent peering la {ix}.",
    },
    "No valid ASNs found in input.": {
        "de": "Keine gültigen ASNs in der Eingabe gefunden.", "fr": "Aucun ASN valide trouvé dans l'entrée.",
        "es": "No se encontraron ASNs válidos en la entrada.", "it": "Nessun ASN valido trovato nell'input.",
        "pt": "Nenhum ASN válido encontrado na entrada.",
        "ru": "В вводе не найдено действительных ASN.", "zh-cn": "输入中未找到有效ASN。", "zh-tw": "輸入中找不到有效的ASN。",
        "ja": "入力に有効なASNが見つかりません。", "cs": "Ve vstupu nebyl nalezen žádný platný ASN.",
        "el": "Δεν βρέθηκαν έγκυρα ASN στην είσοδο.", "lt": "Įvestyje nėra tinkamų ASN.",
        "ro": "Nu s-au găsit ASN-uri valide în intrare.",
    },
    # ── UI controls ───────────────────────────────────────────────────────────
    "Toggle columns": {
        "de": "Spalten ein-/ausblenden", "fr": "Afficher/masquer les colonnes",
        "es": "Alternar columnas", "it": "Attiva/disattiva colonne",
        "pt": "Alternar colunas",
        "ru": "Переключить столбцы", "zh-cn": "切换列", "zh-tw": "切換欄位",
        "ja": "列の表示切替", "cs": "Přepnout sloupce", "el": "Εναλλαγή στηλών",
        "lt": "Perjungti stulpelius", "ro": "Comutare coloane",
    },
    "Type to filter...": {
        "de": "Zum Filtern tippen...", "fr": "Tapez pour filtrer...",
        "es": "Escriba para filtrar...", "it": "Digita per filtrare...",
        "pt": "Escreva para filtrar...",
        "ru": "Введите для фильтрации...", "zh-cn": "输入以筛选...", "zh-tw": "輸入以篩選...",
        "ja": "入力してフィルタ...", "cs": "Pište pro filtraci...", "el": "Πληκτρολογήστε για φιλτράρισμα...",
        "lt": "Įveskite filtrui...", "ro": "Tastați pentru a filtra...",
    },
    "Filter table rows": {
        "de": "Tabellenzeilen filtern", "fr": "Filtrer les lignes du tableau",
        "es": "Filtrar filas de la tabla", "it": "Filtra righe tabella",
        "pt": "Filtrar linhas da tabela",
        "ru": "Фильтр строк таблицы", "zh-cn": "过滤表格行", "zh-tw": "篩選表格行",
        "ja": "テーブル行をフィルタ", "cs": "Filtrovat řádky tabulky", "el": "Φιλτράρισμα γραμμών πίνακα",
        "lt": "Filtruoti lentelės eilutes", "ro": "Filtrare rânduri tabel",
    },
    "Select...": {
        "de": "Auswählen...", "fr": "Sélectionner...", "es": "Seleccionar...",
        "it": "Seleziona...", "pt": "Selecionar...",
        "ru": "Выберите...", "zh-cn": "选择...", "zh-tw": "選擇...",
        "ja": "選択...", "cs": "Vyberte...", "el": "Επιλογή...",
        "lt": "Pasirinkite...", "ro": "Selectați...",
    },
    "Search by name or ASN...": {
        "de": "Nach Name oder ASN suchen...", "fr": "Recherche par nom ou ASN...",
        "es": "Buscar por nombre o ASN...", "it": "Cerca per nome o ASN...",
        "pt": "Pesquisar por nome ou ASN...",
        "ru": "Поиск по имени или ASN...", "zh-cn": "按名称或ASN搜索...", "zh-tw": "按名稱或ASN搜尋...",
        "ja": "名前またはASNで検索...", "cs": "Hledat podle jména nebo ASN...", "el": "Αναζήτηση με όνομα ή ASN...",
        "lt": "Ieškoti pagal pavadinimą ar ASN...", "ro": "Căutare după nume sau ASN...",
    },
    "Search networks, exchanges, facilities": {
        "de": "Netzwerke, Austauschpunkte, Einrichtungen suchen",
        "fr": "Rechercher des réseaux, échanges, installations",
        "es": "Buscar redes, intercambios, instalaciones",
        "it": "Cerca reti, scambi, strutture",
        "pt": "Pesquisar redes, trocas, instalações",
        "ru": "Поиск сетей, IXP, объектов",
        "zh-cn": "搜索网络、交换点、设施",
        "zh-tw": "搜尋網路、交換點、設施",
        "ja": "ネットワーク、IXP、施設を検索",
        "cs": "Hledat sítě, výměny, objekty",
        "el": "Αναζήτηση δικτύων, ανταλλαγών, εγκαταστάσεων",
        "lt": "Ieškoti tinklų, mainų taškų, pastatų",
        "ro": "Căutare rețele, schimburi, facilități",
    },
    "Searching...": {
        "de": "Suche läuft...", "fr": "Recherche en cours...", "es": "Buscando...",
        "it": "Ricerca in corso...", "pt": "A pesquisar...",
        "ru": "Выполняется поиск...", "zh-cn": "搜索中...", "zh-tw": "搜尋中...",
        "ja": "検索中...", "cs": "Hledám...", "el": "Αναζήτηση...",
        "lt": "Ieškoma...", "ro": "Se caută...",
    },
    "Copy as CSV": {
        "de": "Als CSV kopieren", "fr": "Copier en CSV", "es": "Copiar como CSV",
        "it": "Copia come CSV", "pt": "Copiar como CSV",
        "ru": "Скопировать как CSV", "zh-cn": "复制为CSV", "zh-tw": "複製為CSV",
        "ja": "CSVとしてコピー", "cs": "Kopírovat jako CSV", "el": "Αντιγραφή ως CSV",
        "lt": "Kopijuoti kaip CSV", "ro": "Copiere ca CSV",
    },
    "Copy as Markdown": {
        "de": "Als Markdown kopieren", "fr": "Copier en Markdown", "es": "Copiar como Markdown",
        "it": "Copia come Markdown", "pt": "Copiar como Markdown",
        "ru": "Скопировать как Markdown", "zh-cn": "复制为Markdown", "zh-tw": "複製為Markdown",
        "ja": "Markdownとしてコピー", "cs": "Kopírovat jako Markdown", "el": "Αντιγραφή ως Markdown",
        "lt": "Kopijuoti kaip Markdown", "ro": "Copiere ca Markdown",
    },
    "Copy shareable link with current table state": {
        "de": "Teilbaren Link mit aktuellem Tabellenstatus kopieren",
        "fr": "Copier le lien partageable avec l'état actuel du tableau",
        "es": "Copiar enlace compartible con el estado actual de la tabla",
        "it": "Copia link condivisibile con lo stato corrente della tabella",
        "pt": "Copiar link partilhável com o estado atual da tabela",
        "ru": "Скопировать ссылку с текущим состоянием таблицы",
        "zh-cn": "复制包含当前表格状态的分享链接",
        "zh-tw": "複製包含目前表格狀態的分享連結",
        "ja": "現在のテーブル状態を含む共有リンクをコピー",
        "cs": "Kopírovat sdílený odkaz s aktuálním stavem tabulky",
        "el": "Αντιγραφή κοινόχρηστου συνδέσμου με τρέχουσα κατάσταση πίνακα",
        "lt": "Kopijuoti dalinimo nuorodą su dabartiniu lentelės statu",
        "ro": "Copiere link partajabil cu starea actuală a tabelului",
    },
    "Export CSV": {
        "de": "CSV exportieren", "fr": "Exporter en CSV", "es": "Exportar CSV",
        "it": "Esporta CSV", "pt": "Exportar CSV",
        "ru": "Экспорт CSV", "zh-cn": "导出CSV", "zh-tw": "匯出CSV",
        "ja": "CSVエクスポート", "cs": "Exportovat CSV", "el": "Εξαγωγή CSV",
        "lt": "Eksportuoti CSV", "ro": "Export CSV",
    },
    "Next page": {
        "de": "Nächste Seite", "fr": "Page suivante", "es": "Página siguiente",
        "it": "Pagina successiva", "pt": "Página seguinte",
        "ru": "Следующая страница", "zh-cn": "下一页", "zh-tw": "下一頁",
        "ja": "次のページ", "cs": "Další stránka", "el": "Επόμενη σελίδα",
        "lt": "Kitas puslapis", "ro": "Pagina următoare",
    },
    "Previous page": {
        "de": "Vorherige Seite", "fr": "Page précédente", "es": "Página anterior",
        "it": "Pagina precedente", "pt": "Página anterior",
        "ru": "Предыдущая страница", "zh-cn": "上一页", "zh-tw": "上一頁",
        "ja": "前のページ", "cs": "Předchozí stránka", "el": "Προηγούμενη σελίδα",
        "lt": "Ankstesnis puslapis", "ro": "Pagina anterioară",
    },
    "Share page": {
        "de": "Seite teilen", "fr": "Partager la page", "es": "Compartir página",
        "it": "Condividi pagina", "pt": "Partilhar página",
        "ru": "Поделиться страницей", "zh-cn": "分享页面", "zh-tw": "分享頁面",
        "ja": "ページを共有", "cs": "Sdílet stránku", "el": "Κοινοποίηση σελίδας",
        "lt": "Dalintis puslapiu", "ro": "Partajare pagină",
    },
    "Current Page": {
        "de": "Aktuelle Seite", "fr": "Page actuelle", "es": "Página actual",
        "it": "Pagina corrente", "pt": "Página atual",
        "ru": "Текущая страница", "zh-cn": "当前页面", "zh-tw": "目前頁面",
        "ja": "現在のページ", "cs": "Aktuální stránka", "el": "Τρέχουσα σελίδα",
        "lt": "Dabartinis puslapis", "ro": "Pagina curentă",
    },
    "✕ Close": {
        "de": "✕ Schließen", "fr": "✕ Fermer", "es": "✕ Cerrar",
        "it": "✕ Chiudi", "pt": "✕ Fechar",
        "ru": "✕ Закрыть", "zh-cn": "✕ 关闭", "zh-tw": "✕ 關閉",
        "ja": "✕ 閉じる", "cs": "✕ Zavřít", "el": "✕ Κλείσιμο",
        "lt": "✕ Uždaryti", "ro": "✕ Închide",
    },
    # ── Rate limiting ─────────────────────────────────────────────────────────
    "Rate Limited": {
        "de": "Ratenbegrenzung", "fr": "Limite de débit", "es": "Límite de velocidad",
        "it": "Limite di velocità", "pt": "Limite de taxa",
        "ru": "Ограничение скорости", "zh-cn": "速率限制", "zh-tw": "速率限制",
        "ja": "レート制限", "cs": "Omezení rychlosti", "el": "Περιορισμός ρυθμού",
        "lt": "Greičio apribojimas", "ro": "Limită de rată",
    },
    "Rate limited — try again shortly": {
        "de": "Ratenbegrenzt — bitte kurz warten",
        "fr": "Limite de débit atteinte — réessayez dans un moment",
        "es": "Límite de velocidad — intente de nuevo en breve",
        "it": "Limite di velocità — riprova tra poco",
        "pt": "Limite de taxa — tente novamente em breve",
        "ru": "Ограничение скорости — повторите попытку позже",
        "zh-cn": "速率受限 — 请稍后重试",
        "zh-tw": "速率受限 — 請稍後重試",
        "ja": "レート制限中 — しばらくしてから再試行してください",
        "cs": "Omezení rychlosti — zkuste to brzy znovu",
        "el": "Περιορισμός ρυθμού — δοκιμάστε ξανά σύντομα",
        "lt": "Greičio apribojimas — bandykite netrukus",
        "ro": "Limită de rată — încercați din nou în scurt timp",
    },
    "Too many requests. Please wait a moment and try again.": {
        "de": "Zu viele Anfragen. Bitte warten Sie einen Moment und versuchen Sie es erneut.",
        "fr": "Trop de requêtes. Veuillez attendre un moment et réessayer.",
        "es": "Demasiadas solicitudes. Por favor espere un momento e intente de nuevo.",
        "it": "Troppe richieste. Attendere un momento e riprovare.",
        "pt": "Demasiados pedidos. Aguarde um momento e tente novamente.",
        "ru": "Слишком много запросов. Подождите немного и повторите попытку.",
        "zh-cn": "请求过多。请等待片刻后重试。",
        "zh-tw": "請求過多。請稍候後重試。",
        "ja": "リクエストが多すぎます。しばらく待ってから再試行してください。",
        "cs": "Příliš mnoho požadavků. Chvíli počkejte a zkuste to znovu.",
        "el": "Πάρα πολλά αιτήματα. Περιμένετε λίγο και δοκιμάστε ξανά.",
        "lt": "Per daug užklausų. Palaukite akimirką ir bandykite dar kartą.",
        "ro": "Prea multe cereri. Așteptați un moment și încercați din nou.",
    },
    "The mirror API is temporarily rate-limiting requests. Data shown may be stale.": {
        "de": "Die Mirror-API begrenzt vorübergehend die Anfragen. Angezeigte Daten können veraltet sein.",
        "fr": "L'API miroir limite temporairement les requêtes. Les données affichées peuvent être obsolètes.",
        "es": "La API espejo está limitando temporalmente las solicitudes. Los datos mostrados pueden estar desactualizados.",
        "it": "L'API specchio sta temporaneamente limitando le richieste. I dati mostrati potrebbero non essere aggiornati.",
        "pt": "A API espelho está temporariamente a limitar os pedidos. Os dados mostrados podem estar desatualizados.",
        "ru": "API зеркала временно ограничивает запросы. Показанные данные могут быть устаревшими.",
        "zh-cn": "镜像API暂时限制了请求速率。显示的数据可能已过期。",
        "zh-tw": "鏡像API暫時限制了請求速率。顯示的資料可能已過期。",
        "ja": "ミラーAPIが一時的にリクエストを制限しています。表示されるデータが古い場合があります。",
        "cs": "Mirror API dočasně omezuje požadavky. Zobrazená data mohou být neaktuální.",
        "el": "Το API αντιγράφου περιορίζει προσωρινά τα αιτήματα. Τα δεδομένα ενδέχεται να μην είναι ενημερωμένα.",
        "lt": "Veidrodinis API laikinai riboja užklausas. Rodomi duomenys gali būti pasenę.",
        "ro": "API-ul oglindă limitează temporar cererile. Datele afișate pot fi depășite.",
    },
    "Dismiss rate limit warning": {
        "de": "Warnung zur Ratenbegrenzung schließen", "fr": "Ignorer l'avertissement de limite",
        "es": "Descartar advertencia de límite", "it": "Chiudi avviso limite",
        "pt": "Dispensar aviso de limite",
        "ru": "Закрыть предупреждение об ограничении", "zh-cn": "忽略速率限制警告", "zh-tw": "忽略速率限制警告",
        "ja": "レート制限の警告を閉じる", "cs": "Zavřít upozornění na omezení", "el": "Απόρριψη προειδοποίησης ορίου",
        "lt": "Atmesti greičio apribojimo įspėjimą", "ro": "Închide avertismentul de limită",
    },
    # ── Sync / mirror status ──────────────────────────────────────────────────
    "Mirror data is up to date with upstream PeeringDB.": {
        "de": "Mirror-Daten sind aktuell mit dem vorgelagerten PeeringDB.",
        "fr": "Les données du miroir sont à jour avec PeeringDB en amont.",
        "es": "Los datos del espejo están actualizados con PeeringDB.",
        "it": "I dati del mirror sono aggiornati con PeeringDB.",
        "pt": "Os dados do espelho estão atualizados com o PeeringDB.",
        "ru": "Данные зеркала актуальны по отношению к вышестоящему PeeringDB.",
        "zh-cn": "镜像数据与上游PeeringDB最新同步。",
        "zh-tw": "鏡像資料與上游PeeringDB保持最新。",
        "ja": "ミラーデータは上流のPeeringDBと最新の状態です。",
        "cs": "Data mirror jsou aktuální vůči upstream PeeringDB.",
        "el": "Τα δεδομένα αντιγράφου είναι ενημερωμένα με το upstream PeeringDB.",
        "lt": "Veidrodžio duomenys yra atnaujinti pagal PeeringDB.",
        "ro": "Datele oglindă sunt actualizate cu PeeringDB upstream.",
    },
    "Mirror data is slightly stale. The sync worker runs every 15 minutes.": {
        "de": "Mirror-Daten sind leicht veraltet. Der Sync-Worker läuft alle 15 Minuten.",
        "fr": "Les données du miroir sont légèrement obsolètes. Le worker de synchronisation tourne toutes les 15 minutes.",
        "es": "Los datos del espejo están ligeramente desactualizados. El worker de sincronización se ejecuta cada 15 minutos.",
        "it": "I dati del mirror sono leggermente obsoleti. Il worker di sync viene eseguito ogni 15 minuti.",
        "pt": "Os dados do espelho estão ligeiramente desatualizados. O worker de sincronização é executado a cada 15 minutos.",
        "ru": "Данные зеркала немного устарели. Воркер синхронизации запускается каждые 15 минут.",
        "zh-cn": "镜像数据略有过时。同步工作器每15分钟运行一次。",
        "zh-tw": "鏡像資料略有延遲。同步工作器每15分鐘執行一次。",
        "ja": "ミラーデータが少し古くなっています。同期ワーカーは15分ごとに実行されます。",
        "cs": "Data mirror jsou mírně zastaralá. Sync worker běží každých 15 minut.",
        "el": "Τα δεδομένα αντιγράφου είναι ελαφρώς παλιά. Ο sync worker τρέχει κάθε 15 λεπτά.",
        "lt": "Veidrodžio duomenys šiek tiek pasenę. Sinchronizacijos darbuotojas veikia kas 15 minučių.",
        "ro": "Datele oglindă sunt ușor depășite. Worker-ul de sincronizare rulează la fiecare 15 minute.",
    },
    "Mirror data is over 1 hour old. The sync worker may have stopped.": {
        "de": "Mirror-Daten sind über 1 Stunde alt. Der Sync-Worker könnte gestoppt haben.",
        "fr": "Les données du miroir ont plus d'1 heure. Le worker de synchronisation a peut-être cessé.",
        "es": "Los datos del espejo tienen más de 1 hora. El worker de sincronización puede haberse detenido.",
        "it": "I dati del mirror hanno più di 1 ora. Il worker di sync potrebbe essersi fermato.",
        "pt": "Os dados do espelho têm mais de 1 hora. O worker de sincronização pode ter parado.",
        "ru": "Данные зеркала старше 1 часа. Воркер синхронизации мог остановиться.",
        "zh-cn": "镜像数据超过1小时。同步工作器可能已停止。",
        "zh-tw": "鏡像資料已超過1小時。同步工作器可能已停止。",
        "ja": "ミラーデータが1時間以上経過しています。同期ワーカーが停止している可能性があります。",
        "cs": "Data mirror jsou starší než 1 hodina. Sync worker mohl zastavit.",
        "el": "Τα δεδομένα αντιγράφου είναι πάνω από 1 ώρα παλιά. Ο sync worker μπορεί να έχει σταματήσει.",
        "lt": "Veidrodžio duomenys senesni nei 1 valanda. Sinchronizacijos darbuotojas galėjo sustoti.",
        "ro": "Datele oglindă au peste 1 oră vechime. Worker-ul de sincronizare s-ar putea fi oprit.",
    },
    "Sync older than 1 hour": {
        "de": "Synchronisation älter als 1 Stunde", "fr": "Synchronisation de plus d'1 heure",
        "es": "Sincronización de más de 1 hora", "it": "Sincronizzazione più vecchia di 1 ora",
        "pt": "Sincronização com mais de 1 hora",
        "ru": "Синхронизация старше 1 часа", "zh-cn": "同步时间超过1小时", "zh-tw": "同步時間超過1小時",
        "ja": "1時間以上前の同期", "cs": "Synchronizace starší než 1 hodina", "el": "Συγχρονισμός παλαιότερος από 1 ώρα",
        "lt": "Sinchronizacija senesnė nei 1 valanda", "ro": "Sincronizare mai veche de 1 oră",
    },
    # ── ASN Verify ────────────────────────────────────────────────────────────
    "Verify ASNs": {
        "de": "ASNs verifizieren", "fr": "Vérifier les ASN", "es": "Verificar ASNs",
        "it": "Verifica ASN", "pt": "Verificar ASNs",
        "ru": "Проверить ASN", "zh-cn": "验证ASN", "zh-tw": "驗證ASN",
        "ja": "ASNを確認", "cs": "Ověřit ASN", "el": "Επαλήθευση ASN",
        "lt": "Tikrinti ASN", "ro": "Verificare ASN-uri",
    },
    "Verifying {count} ASNs...": {
        "de": "{count} ASNs werden überprüft...", "fr": "Vérification de {count} ASN...",
        "es": "Verificando {count} ASNs...", "it": "Verifica di {count} ASN...",
        "pt": "A verificar {count} ASNs...",
        "ru": "Проверка {count} ASN...", "zh-cn": "正在验证 {count} 个ASN...", "zh-tw": "正在驗證 {count} 個ASN...",
        "ja": "{count}件のASNを確認中...", "cs": "Ověřování {count} ASN...", "el": "Επαλήθευση {count} ASN...",
        "lt": "Tikrinami {count} ASN...", "ro": "Se verifică {count} ASN-uri...",
    },
    "Enter a list of ASNs (one per line or comma-separated) to check their PeeringDB registration and connectivity.": {
        "de": "Geben Sie eine Liste von ASNs (eine pro Zeile oder durch Komma getrennt) ein, um deren PeeringDB-Registrierung zu überprüfen.",
        "fr": "Saisissez une liste d'ASN (un par ligne ou séparés par des virgules) pour vérifier leur enregistrement PeeringDB.",
        "es": "Introduzca una lista de ASNs (uno por línea o separados por coma) para verificar su registro en PeeringDB.",
        "it": "Inserisci un elenco di ASN (uno per riga o separati da virgola) per verificare la registrazione PeeringDB.",
        "pt": "Introduza uma lista de ASNs (um por linha ou separados por vírgula) para verificar o seu registo no PeeringDB.",
        "ru": "Введите список ASN (по одному в строке или через запятую) для проверки их регистрации в PeeringDB.",
        "zh-cn": "输入ASN列表（每行一个或逗号分隔）以检查其PeeringDB注册情况。",
        "zh-tw": "輸入ASN列表（每行一個或逗號分隔）以檢查其PeeringDB登錄情況。",
        "ja": "ASNのリストを入力してください（1行または1コンマ区切り）、PeeringDB登録と接続性を確認します。",
        "cs": "Zadejte seznam ASN (po jednom na řádek nebo oddělených čárkou) pro kontrolu jejich registrace v PeeringDB.",
        "el": "Εισάγετε μια λίστα ASN (ένα ανά γραμμή ή διαχωρισμένα με κόμμα) για έλεγχο εγγραφής στο PeeringDB.",
        "lt": "Įveskite ASN sąrašą (po vieną eilutėje arba atskirti kableliu), kad patikrintumėte jų registraciją PeeringDB.",
        "ro": "Introduceți o listă de ASN-uri (câte unul pe linie sau separate prin virgulă) pentru a verifica înregistrarea lor în PeeringDB.",
    },
    "e.g. 13335, 20940, 15169": {"*": "e.g. 13335, 20940, 15169"},
    # ── Cache / diagnostics ───────────────────────────────────────────────────
    "All Cached Requests": {
        "de": "Alle gecachten Anfragen", "fr": "Toutes les requêtes en cache",
        "es": "Todas las solicitudes en caché", "it": "Tutte le richieste in cache",
        "pt": "Todos os pedidos em cache",
        "ru": "Все кэшированные запросы", "zh-cn": "所有缓存请求", "zh-tw": "所有快取請求",
        "ja": "全キャッシュリクエスト", "cs": "Všechny uložené požadavky", "el": "Όλα τα αποθηκευμένα αιτήματα",
        "lt": "Visos talpyklos užklausos", "ro": "Toate cererile cache",
    },
    "Cache empty": {
        "de": "Cache leer", "fr": "Cache vide", "es": "Caché vacía",
        "it": "Cache vuota", "pt": "Cache vazia",
        "ru": "Кэш пуст", "zh-cn": "缓存为空", "zh-tw": "快取為空",
        "ja": "キャッシュ空", "cs": "Mezipaměť prázdná", "el": "Κενή κρυφή μνήμη",
        "lt": "Talpykla tuščia", "ro": "Cache gol",
    },
    "No cached API requests for this page": {
        "de": "Keine gecachten API-Anfragen für diese Seite.",
        "fr": "Aucune requête API en cache pour cette page.",
        "es": "No hay solicitudes de API en caché para esta página.",
        "it": "Nessuna richiesta API in cache per questa pagina.",
        "pt": "Nenhum pedido de API em cache para esta página.",
        "ru": "Нет кэшированных запросов API для этой страницы.",
        "zh-cn": "此页面没有缓存的API请求。",
        "zh-tw": "此頁面沒有快取的API請求。",
        "ja": "このページのキャッシュされたAPIリクエストはありません。",
        "cs": "Žádné uložené API požadavky pro tuto stránku.",
        "el": "Δεν υπάρχουν αποθηκευμένα αιτήματα API για αυτή τη σελίδα.",
        "lt": "Nėra talpykloje saugomų API užklausų šiam puslapiui.",
        "ro": "Nicio cerere API cache pentru această pagină.",
    },
    "Session page cache": {
        "de": "Seitencache der Sitzung", "fr": "Cache de page de session",
        "es": "Caché de página de sesión", "it": "Cache pagina sessione",
        "pt": "Cache de página de sessão",
        "ru": "Кэш страниц сессии", "zh-cn": "会话页面缓存", "zh-tw": "工作階段頁面快取",
        "ja": "セッションページキャッシュ", "cs": "Mezipaměť stránek sezení", "el": "Κρυφή μνήμη σελίδων συνεδρίας",
        "lt": "Sesijos puslapio talpykla", "ro": "Cache pagini sesiune",
    },
    "Clear Session Cache": {
        "de": "Sitzungscache leeren", "fr": "Vider le cache de session",
        "es": "Limpiar caché de sesión", "it": "Svuota cache sessione",
        "pt": "Limpar cache de sessão",
        "ru": "Очистить кэш сессии", "zh-cn": "清除会话缓存", "zh-tw": "清除工作階段快取",
        "ja": "セッションキャッシュをクリア", "cs": "Vymazat mezipaměť sezení", "el": "Εκκαθάριση κρυφής μνήμης συνεδρίας",
        "lt": "Išvalyti sesijos talpyklą", "ro": "Golire cache sesiune",
    },
    "Clear Browser Cache": {
        "de": "Browser-Cache leeren", "fr": "Vider le cache du navigateur",
        "es": "Limpiar caché del navegador", "it": "Svuota cache browser",
        "pt": "Limpar cache do navegador",
        "ru": "Очистить кэш браузера", "zh-cn": "清除浏览器缓存", "zh-tw": "清除瀏覽器快取",
        "ja": "ブラウザキャッシュをクリア", "cs": "Vymazat mezipaměť prohlížeče", "el": "Εκκαθάριση κρυφής μνήμης προγράμματος περιήγησης",
        "lt": "Išvalyti naršyklės talpyklą", "ro": "Golire cache browser",
    },
    "Force Reload": {
        "de": "Erzwungene Neuladung", "fr": "Rechargement forcé", "es": "Recarga forzada",
        "it": "Ricarica forzata", "pt": "Recarregamento forçado",
        "ru": "Принудительная перезагрузка", "zh-cn": "强制重新加载", "zh-tw": "強制重新載入",
        "ja": "強制リロード", "cs": "Vynucené načtení", "el": "Αναγκαστική επαναφόρτωση",
        "lt": "Priverstinis perkrovimas", "ro": "Reîncărcare forțată",
    },
    "D1 Edge Sync State": {"*": "D1 Edge Sync State"},
    "Pipeline Diagnostics": {
        "de": "Pipeline-Diagnose", "fr": "Diagnostics du pipeline", "es": "Diagnósticos de pipeline",
        "it": "Diagnostica pipeline", "pt": "Diagnósticos de pipeline",
        "ru": "Диагностика конвейера", "zh-cn": "管道诊断", "zh-tw": "管道診斷",
        "ja": "パイプライン診断", "cs": "Diagnostika pipeliny", "el": "Διαγνωστικά αγωγού",
        "lt": "Vamzdyno diagnostika", "ro": "Diagnostice pipeline",
    },
    "Loading telemetry...": {
        "de": "Telemetrie wird geladen...", "fr": "Chargement de la télémétrie...",
        "es": "Cargando telemetría...", "it": "Caricamento telemetria...",
        "pt": "A carregar telemetria...",
        "ru": "Загрузка телеметрии...", "zh-cn": "正在加载遥测数据...", "zh-tw": "正在載入遙測資料...",
        "ja": "テレメトリを読み込み中...", "cs": "Načítání telemetrie...", "el": "Φόρτωση τηλεμετρίας...",
        "lt": "Kraunama telemetrija...", "ro": "Se încarcă telemetria...",
    },
    "Failed to load telemetry": {
        "de": "Telemetrie konnte nicht geladen werden", "fr": "Impossible de charger la télémétrie",
        "es": "No se pudo cargar la telemetría", "it": "Caricamento telemetria non riuscito",
        "pt": "Falha ao carregar telemetria",
        "ru": "Не удалось загрузить телеметрию", "zh-cn": "无法加载遥测数据", "zh-tw": "無法載入遙測資料",
        "ja": "テレメトリの読み込みに失敗", "cs": "Telemetrii nelze načíst", "el": "Αδυναμία φόρτωσης τηλεμετρίας",
        "lt": "Nepavyko įkelti telemetrijos", "ro": "Imposibil de încărcat telemetria",
    },
    "Served By": {
        "de": "Bereitgestellt von", "fr": "Servi par", "es": "Servido por",
        "it": "Servito da", "pt": "Servido por",
        "ru": "Обслуживается", "zh-cn": "由...提供服务", "zh-tw": "由...提供服務",
        "ja": "提供元", "cs": "Poskytováno", "el": "Εξυπηρετείται από",
        "lt": "Aptarnauja", "ro": "Servit de",
    },
    "Loading affiliations": {
        "de": "Zugehörigkeiten werden geladen", "fr": "Chargement des affiliations",
        "es": "Cargando afiliaciones", "it": "Caricamento affiliazioni",
        "pt": "A carregar afiliações",
        "ru": "Загрузка аффилиаций", "zh-cn": "正在加载关联", "zh-tw": "正在載入關聯",
        "ja": "アフィリエーションを読み込み中", "cs": "Načítání příslušností", "el": "Φόρτωση συνδέσεων",
        "lt": "Kraunamos priklausomybės", "ro": "Se încarcă afilierile",
    },
    # ── Account ───────────────────────────────────────────────────────────────
    "Revoke API key": {
        "de": "API-Schlüssel widerrufen", "fr": "Révoquer la clé API",
        "es": "Revocar clave API", "it": "Revoca chiave API",
        "pt": "Revogar chave API",
        "ru": "Отозвать ключ API", "zh-cn": "撤销API密钥", "zh-tw": "撤銷API金鑰",
        "ja": "APIキーを無効化", "cs": "Odvolat API klíč", "el": "Ανάκληση κλειδιού API",
        "lt": "Atšaukti API raktą", "ro": "Revocare cheie API",
    },
    "Copy this key now \u2014 it will not be shown again.": {
        "de": "Kopieren Sie diesen Schlüssel jetzt — er wird nicht erneut angezeigt.",
        "fr": "Copiez cette clé maintenant — elle ne sera plus affichée.",
        "es": "Copie esta clave ahora — no se mostrará de nuevo.",
        "it": "Copia questa chiave ora — non verrà mostrata di nuovo.",
        "pt": "Copie esta chave agora — não será mostrada novamente.",
        "ru": "Скопируйте этот ключ сейчас — он больше не будет показан.",
        "zh-cn": "请立即复制此密钥 — 它不会再次显示。",
        "zh-tw": "請立即複製此金鑰 — 它不會再次顯示。",
        "ja": "今すぐこのキーをコピーしてください — 再表示されません。",
        "cs": "Zkopírujte tento klíč nyní — nebude znovu zobrazen.",
        "el": "Αντιγράψτε αυτό το κλειδί τώρα — δεν θα εμφανιστεί ξανά.",
        "lt": "Nukopijuokite šį raktą dabar — jis nebus rodomas vėl.",
        "ro": "Copiați această cheie acum — nu va mai fi afișată.",
    },
    'e.g. "curl scripts"': {
        "de": 'z.B. „Curl-Skripte"', "fr": 'ex. « scripts curl »',
        "es": 'p.ej. "scripts curl"', "it": 'es. "script curl"',
        "pt": 'ex.: "scripts curl"',
        "ru": 'напр. «curl скрипты»', "zh-cn": '例如"curl 脚本"', "zh-tw": '例如「curl 腳本」',
        "ja": '例：「curlスクリプト」', "cs": 'např. „curl skripty"', "el": 'π.χ. "scripts curl"',
        "lt": 'pvz. „curl skriptai"', "ro": 'ex. „scripturi curl"',
    },
    "Go to your profile on PeeringDB": {
        "de": "Zu Ihrem PeeringDB-Profil", "fr": "Accéder à votre profil PeeringDB",
        "es": "Ir a su perfil en PeeringDB", "it": "Vai al tuo profilo su PeeringDB",
        "pt": "Ir para o seu perfil no PeeringDB",
        "ru": "Перейти в профиль PeeringDB", "zh-cn": "前往您的PeeringDB个人资料", "zh-tw": "前往您在PeeringDB的個人資料",
        "ja": "PeeringDBのプロフィールへ", "cs": "Přejít na svůj profil v PeeringDB", "el": "Μεταβείτε στο προφίλ σας στο PeeringDB",
        "lt": "Eiti į savo PeeringDB profilį", "ro": "Mergeți la profilul dvs. pe PeeringDB",
    },
    "Direct Membership Details": {
        "de": "Details zur direkten Mitgliedschaft", "fr": "Détails de l'adhésion directe",
        "es": "Detalles de membresía directa", "it": "Dettagli appartenenza diretta",
        "pt": "Detalhes de adesão direta",
        "ru": "Сведения о прямом членстве", "zh-cn": "直接成员资格详情", "zh-tw": "直接成員資格詳情",
        "ja": "直接メンバーシップの詳細", "cs": "Podrobnosti o přímém členství", "el": "Λεπτομέρειες άμεσης συνδρομής",
        "lt": "Tiesioginės narystės detalės", "ro": "Detalii despre apartenența directă",
    },
    # ── Long descriptions ─────────────────────────────────────────────────────
    "Select two Networks, Exchanges, or Facilities below to see where their infrastructure overlaps. The comparison shows shared and exclusive resources: which IXPs both networks peer at, which facilities they both occupy, or which members two exchanges have in common.": {
        "de": "Wählen Sie unten zwei Netzwerke, Austauschpunkte oder Einrichtungen aus, um deren gemeinsame Infrastruktur zu sehen.",
        "fr": "Sélectionnez deux réseaux, échanges ou installations ci-dessous pour voir où leur infrastructure se recoupe.",
        "es": "Seleccione dos redes, intercambios o instalaciones abajo para ver dónde se superpone su infraestructura.",
        "it": "Seleziona due reti, scambi o strutture qui sotto per vedere dove la loro infrastruttura si sovrappone.",
        "pt": "Selecione duas redes, trocas ou instalações abaixo para ver onde a sua infraestrutura se sobrepõe.",
        "ru": "Выберите ниже два объекта (сеть, IXP или объект), чтобы увидеть общую инфраструктуру.",
        "zh-cn": "在下方选择两个网络、交换点或设施，查看其基础设施的重叠部分。",
        "zh-tw": "在下方選擇兩個網路、交換點或設施，查看其基礎設施的重疊部分。",
        "ja": "下で2つのネットワーク、IXP、または施設を選択して共有インフラを確認します。",
        "cs": "Vyberte níže dvě sítě, výměny nebo objekty a zjistěte, kde se jejich infrastruktura překrývá.",
        "el": "Επιλέξτε παρακάτω δύο δίκτυα, ανταλλαγές ή εγκαταστάσεις για να δείτε που επικαλύπτεται η υποδομή τους.",
        "lt": "Žemiau pasirinkite du tinklus, mainų taškus ar pastatus, kad pamatytumėte jų infrastruktūros persidengimą.",
        "ro": "Selectați mai jos două rețele, schimburi sau facilități pentru a vedea unde se suprapune infrastructura lor.",
    },
    "Analyze overlapping infrastructure between two entities.": {
        "de": "Überlappende Infrastruktur zwischen zwei Entitäten analysieren.",
        "fr": "Analyser l'infrastructure qui se recoupe entre deux entités.",
        "es": "Analizar la infraestructura superpuesta entre dos entidades.",
        "it": "Analizzare l'infrastruttura sovrapposta tra due entità.",
        "pt": "Analisar a infraestrutura sobreposta entre duas entidades.",
        "ru": "Анализ общей инфраструктуры между двумя объектами.",
        "zh-cn": "分析两个实体之间的重叠基础设施。",
        "zh-tw": "分析兩個實體之間的重疊基礎設施。",
        "ja": "2つのエンティティ間の重複インフラを分析します。",
        "cs": "Analyzovat překrývající se infrastrukturu mezi dvěma subjekty.",
        "el": "Ανάλυση επικαλυπτόμενης υποδομής μεταξύ δύο οντοτήτων.",
        "lt": "Analizuoti besikertančią infrastruktūrą tarp dviejų subjektų.",
        "ro": "Analizați infrastructura suprapusă între două entități.",
    },
    "Results are split into three sections: resources shared by both entities, resources exclusive to entity A, and resources exclusive to entity B. Use this to evaluate redundancy, identify potential peering opportunities, or plan infrastructure expansion.": {
        "de": "Ergebnisse sind in drei Abschnitte unterteilt: gemeinsame Ressourcen, exklusive Ressourcen von A, exklusive Ressourcen von B.",
        "fr": "Les résultats sont divisés en trois sections : ressources partagées, ressources exclusives à A et exclusives à B.",
        "es": "Los resultados se dividen en tres secciones: recursos compartidos, recursos exclusivos de A y recursos exclusivos de B.",
        "it": "I risultati sono divisi in tre sezioni: risorse condivise, risorse esclusive di A e risorse esclusive di B.",
        "pt": "Os resultados estão divididos em três secções: recursos partilhados, recursos exclusivos de A e recursos exclusivos de B.",
        "ru": "Результаты разделены на три раздела: общие ресурсы, эксклюзивные для A и эксклюзивные для B.",
        "zh-cn": "结果分为三部分：两个实体共享的资源、仅A拥有的资源以及仅B拥有的资源。",
        "zh-tw": "結果分為三部分：兩個實體共享的資源、僅A擁有的資源以及僅B擁有的資源。",
        "ja": "結果は3つのセクションに分かれています：両エンティティで共有するリソース、Aのみのリソース、Bのみのリソース。",
        "cs": "Výsledky jsou rozděleny do tří sekcí: sdílené zdroje, výhradní zdroje pro A a výhradní zdroje pro B.",
        "el": "Τα αποτελέσματα χωρίζονται σε τρεις ενότητες: κοινοί πόροι, αποκλειστικοί για το Α και αποκλειστικοί για το Β.",
        "lt": "Rezultatai skirstomi į tris skyrius: abiejų subjektų bendri ištekliai, išskirtiniai A ištekliai ir išskirtiniai B ištekliai.",
        "ro": "Rezultatele sunt împărțite în trei secțiuni: resurse partajate, resurse exclusive pentru A și resurse exclusive pentru B.",
    },
    # ── Advanced Search ───────────────────────────────────────────────────────
    "Advanced Search": {
        "de": "Erweiterte Suche", "fr": "Recherche avancée", "es": "Búsqueda avanzada",
        "it": "Ricerca avanzata", "pt": "Pesquisa avançada",
        "ru": "Расширенный поиск", "zh-cn": "高级搜索", "zh-tw": "進階搜尋",
        "ja": "高度な検索", "cs": "Rozšířené vyhledávání", "el": "Σύνθετη αναζήτηση",
        "lt": "Išplėstinė paieška", "ro": "Căutare avansată",
    },
    "limit reached — refine your search": {
        "de": "Limit erreicht — verfeinern Sie Ihre Suche",
        "fr": "Limite atteinte — affinez votre recherche",
        "es": "Límite alcanzado — refine su búsqueda",
        "it": "Limite raggiunto — affina la ricerca",
        "pt": "Limite atingido — refine a sua pesquisa",
        "ru": "Лимит достигнут — уточните поиск",
        "zh-cn": "已达上限 — 请精细化您的搜索条件",
        "zh-tw": "已達上限 — 請精細化您的搜尋條件",
        "ja": "上限に達しました — 検索を絞り込んでください",
        "cs": "Dosažen limit — zpřesněte vyhledávání",
        "el": "Επετεύχθη το όριο — βελτιώστε την αναζήτησή σας",
        "lt": "Limitas pasiektas — patikslinkite paiešką",
        "ro": "Limita atinsă — rafinați căutarea",
    },
    "Does not matter": {
        "de": "Keine Rolle", "fr": "Peu importe", "es": "No importa",
        "it": "Non importa", "pt": "Não importa",
        "ru": "Не важно", "zh-cn": "无所谓", "zh-tw": "無所謂",
        "ja": "問わない", "cs": "Nezáleží", "el": "Δεν έχει σημασία",
        "lt": "Nesvarbu", "ro": "Nu contează",
    },
}

# ── Write to override files ───────────────────────────────────────────────────

all_langs = ["cs", "de", "el", "es", "fr", "it", "ja", "lt", "pt", "ro", "ru", "zh-cn", "zh-tw"]

for lang in all_langs:
    path = OVERRIDES_DIR / f"{lang}.json"
    existing = json.loads(path.read_text()) if path.exists() else {}

    added = 0
    for en_key, trans in TRANSLATIONS.items():
        if en_key in existing:
            continue  # already translated, don't overwrite
        if "*" in trans:
            existing[en_key] = trans["*"]
            added += 1
        elif lang in trans:
            existing[en_key] = trans[lang]
            added += 1
        # If no translation available for this lang, skip (leave for t() fallback)

    # Re-sort: metadata keys first, then alphabetical
    meta = {k: v for k, v in existing.items() if k.startswith("_")}
    data = {k: v for k, v in existing.items() if not k.startswith("_")}
    merged = {**meta, **dict(sorted(data.items()))}

    path.write_text(json.dumps(merged, ensure_ascii=False, indent=2) + "\n")
    print(f"  {lang}: +{added} strings")

print("\nDone.")
