/**
 * @fileoverview GraphQL worker entry point.
 *
 * Serves a GraphQL API over the PeeringDB dataset using graphql-yoga.
 * The schema and resolvers are generated by scripts/gen_graphql_schema.py
 * from the extracted entity definitions.
 *
 * Architecture:
 *   - handlers/query.js   — POST caching via SWR + yoga execution
 *   - handlers/static.js  — GraphiQL landing page + font assets
 *   - cache.js            — LRU cache, cache key generation, SWR wrapper
 *   - Auth via core/auth.js (API keys + session cookies)
 *   - Rate limiting via core/ratelimit.js factory
 *   - L2 cache via core/pipeline/ with SHA-256 hashed keys
 *
 * Route: graphql.pdbfe.dev/*
 */

import { resolveAuth } from '../core/auth.js';
import { wrapHandler, validateRequest, routeAdminPath } from '../core/admin.js';
import { handlePreflight, jsonError } from '../core/http.js';
import { parseURL } from '../core/utils.js';
import { initL2 } from '../core/pipeline/index.js';
import { createRateLimiter } from '../core/ratelimit.js';
import { getGqlCacheStats, purgeGqlCache } from './cache.js';
import { serveStaticAsset } from './handlers/static.js';
import { handleQuery, handleUncached } from './handlers/query.js';

/**
 * Rate limiter instance for GraphQL requests.
 * Lower throughput than the API worker — GraphQL queries tend to be
 * heavier, so we allow fewer requests per window.
 */
const { isRateLimited, getStats: getRateLimitStats, purge: purgeRateLimit } = createRateLimiter({
    slots: 2000,
    maxBytes: 2 * 1024 * 1024,
    windowMs: 60_000,
    limitAnon: 30,
    limitAuth: 300,
});

/**
 * Handles incoming requests to the GraphQL worker.
 *
 * Flow:
 *   1. L2 cache initialisation (needs origin URL for key prefix)
 *   2. CORS preflight handling
 *   3. Admin endpoints (health, robots.txt, cache stats)
 *   4. Static assets (GraphiQL, fonts)
 *   5. Auth resolution
 *   6. Rate limiting
 *   7. Delegate to query handler (POST) or uncached yoga (GET/HEAD)
 *
 * @param {Request} request - The inbound HTTP request.
 * @param {PdbApiEnv} env - Cloudflare environment bindings.
 * @param {ExecutionContext} ctx - Worker execution context.
 * @returns {Promise<Response>} The HTTP response.
 */
async function handleRequest(request, env, ctx) {
    initL2(request.url);
    const { rawPath } = parseURL(request);

    // Validate request method and path
    const validationError = validateRequest(request, rawPath, ['GET', 'POST', 'HEAD', 'OPTIONS']);
    if (validationError) return validationError;

    // CORS preflight
    if (request.method === 'OPTIONS') {
        return handlePreflight(request);
    }

    // D1 session for read replication
    const db = env.PDB.withSession('first-unconstrained');

    // Admin endpoints (/_admin/*, /robots.txt, /health)
    const adminResponse = await routeAdminPath(rawPath, env, {
        db,
        serviceName: 'pdbfe-graphql',
        getStats: () => ({
            graphql: getGqlCacheStats(),
            rateLimit: getRateLimitStats(),
        }),
        flush: () => { purgeGqlCache(); purgeRateLimit(); },
    });
    if (adminResponse) return adminResponse;

    // Static assets (GraphiQL page, CSS/Font bundles)
    const staticResponse = serveStaticAsset(request, rawPath);
    if (staticResponse) return staticResponse;

    // Auth resolution
    const { authenticated, identity, rejection } = await resolveAuth(request, env);
    if (rejection) return jsonError(403, rejection);

    // Rate limiting
    const clientIP = request.headers.get('cf-connecting-ip') || 'unknown';
    const callerKey = identity || clientIP;
    const now = Date.now();
    if (isRateLimited(callerKey, authenticated, now)) {
        return jsonError(429, 'Rate limit exceeded. Try again later.');
    }

    // POST → cached query pipeline (returns null on negative cache bypass)
    const cached = await handleQuery(request, db, ctx, authenticated);
    if (cached) return cached;

    // Fallback: uncached yoga for non-POST, HEAD, or negative-cache bypass
    return handleUncached(request, db, authenticated);
}

export default wrapHandler(handleRequest, 'pdbfe-graphql');
