/**
 * @fileoverview GraphQL worker entry point.
 *
 * Serves a GraphQL API over the PeeringDB dataset using graphql-yoga.
 * The schema and resolvers are generated by scripts/gen_graphql_schema.py
 * from the extracted entity definitions.
 *
 * Architecture:
 *   - graphql-yoga handles the HTTP layer (POST parsing)
 *   - Browser landing page: frontend/api/graphql.html (imported at bundle time)
 *   - Resolvers use the shared query builder from workers/api/query.js
 *   - Auth via core/auth.js (API keys + session cookies)
 *   - Rate limiting via core/ratelimit.js factory
 *   - L2 cache via core/l2cache.js with SHA-256 hashed keys
 *
 * Route: graphql.pdbfe.dev/*
 */

import { createSchema, createYoga } from 'graphql-yoga';
import { typeDefs } from '../../extracted/graphql-typedefs.js';
import { resolvers } from '../../extracted/graphql-resolvers.js';
import { resolveAuth } from '../core/auth.js';
import { wrapHandler, validateRequest, routeAdminPath } from '../core/admin.js';
import { handlePreflight, jsonError } from '../core/http.js';
import { parseURL } from '../core/utils.js';
import { initL2 } from '../core/l2cache.js';
import { createRateLimiter, normaliseIP } from '../core/ratelimit.js';
import { getGqlCacheStats, purgeGqlCache } from './cache.js';
import GRAPHIQL_HTML from '../../frontend/api/graphql.html';

/**
 * Rate limiter instance for GraphQL requests.
 * Lower throughput than the API worker — GraphQL queries tend to be
 * heavier, so we allow fewer requests per window.
 */
const { isRateLimited, getStats: getRateLimitStats, purge: purgeRateLimit } = createRateLimiter({
    slots: 2000,
    maxBytes: 2 * 1024 * 1024,
    windowMs: 60_000,
    limitAnon: 30,
    limitAuth: 300,
});

/** Pre-built headers for the GraphiQL HTML page. */
const H_GRAPHIQL = Object.freeze({
    'Content-Type': 'text/html; charset=utf-8',
    'Cache-Control': 'public, max-age=3600',
});

/**
 * Lazily initialised graphql-yoga instance.
 * Created on first request to avoid cold-start overhead when the
 * isolate is recycled. Module-scoped singleton pattern.
 * @type {ReturnType<typeof createYoga>|null}
 */
let _yoga = null;

/**
 * Returns the graphql-yoga instance, creating it on first call.
 * The schema is compiled once and reused for the isolate lifetime.
 * GraphiQL is disabled — we serve our own branded page instead.
 *
 * @returns {ReturnType<typeof createYoga>} The yoga instance.
 */
function getYoga() {
    if (!_yoga) {
        _yoga = createYoga({
            schema: createSchema({ typeDefs, resolvers }),
            graphiql: false,
            landingPage: false,
        });
    }
    return _yoga;
}

/**
 * Checks whether a request is a browser navigation (GET with Accept: text/html).
 *
 * @param {Request} request - The inbound request.
 * @returns {boolean} True if this looks like a browser navigation.
 */
function isBrowserGet(request) {
    if (request.method !== 'GET') return false;
    const accept = request.headers.get('Accept') || '';
    return accept.includes('text/html');
}

/**
 * Handles incoming requests to the GraphQL worker.
 *
 * Flow:
 *   1. L2 cache initialisation (needs origin URL for key prefix)
 *   2. CORS preflight handling
 *   3. Admin endpoints (health, robots.txt, cache stats)
 *   4. Browser GET → branded GraphiQL page
 *   5. Auth resolution
 *   6. Rate limiting
 *   7. Delegate to graphql-yoga
 *
 * @param {Request} request - The inbound HTTP request.
 * @param {PdbApiEnv} env - Cloudflare environment bindings.
 * @param {ExecutionContext} ctx - Worker execution context.
 * @returns {Promise<Response>} The HTTP response.
 */
async function handleRequest(request, env, ctx) {
    initL2(request.url);
    const { rawPath } = parseURL(request);

    // Validate request method and path
    const validationError = validateRequest(request, rawPath, ['GET', 'POST', 'HEAD', 'OPTIONS']);
    if (validationError) return validationError;

    // CORS preflight
    if (request.method === 'OPTIONS') {
        return handlePreflight(request);
    }

    // D1 session for read replication
    const db = env.PDB.withSession('first-unconstrained');

    // Admin endpoints (/_admin/*, /robots.txt, /health)
    const adminResponse = await routeAdminPath(request, rawPath, env, ctx, {
        db,
        serviceName: 'pdbfe-graphql',
        getStats: () => ({
            graphql: getGqlCacheStats(),
            rateLimit: getRateLimitStats(),
        }),
        flush: () => { purgeGqlCache(); purgeRateLimit(); },
    });
    if (adminResponse) return adminResponse;

    // Browser navigation → branded GraphiQL page
    // Matches both root (graphql.pdbfe.dev/) and path-based route (api.pdbfe.dev/graphql)
    if ((rawPath === '' || rawPath === 'graphql') && isBrowserGet(request)) {
        return new Response(GRAPHIQL_HTML, { status: 200, headers: H_GRAPHIQL });
    }

    // Auth resolution
    const { authenticated, identity, rejection } = await resolveAuth(request, env);
    if (rejection) return jsonError(403, rejection);

    // Rate limiting
    const callerKey = identity || normaliseIP(request);
    const now = Date.now();
    if (isRateLimited(callerKey, authenticated, now)) {
        return jsonError(429, 'Rate limit exceeded. Try again later.');
    }

    // Delegate to graphql-yoga with D1 and auth context
    const yoga = getYoga();
    return yoga.fetch(request, { db, authenticated });
}

export default wrapHandler(handleRequest, 'pdbfe-graphql');
